const PLAYER_DATA = [
    {
        "TIER":  "2",
        "PLAYER":  "Bruce Branch III",
        "TEAM/HS":  "Prolific Prep ",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Scoring Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "4",
        "247":  "8",
        "ESPN":  "6",
        "MADE":  "2",
        "EBY":  "1",
        "CONSENSUS":  "4.2",
        "INDUSTRY PRO":  "5",
        "EBY DIFF INDUSTRY":  "4"
    },
    {
        "TIER":  "2",
        "PLAYER":  "Dylan Mingo ",
        "TEAM/HS":  "Long Island Lutheran",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Primary Initiator",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00273\"",
        "RIVALS":  "2",
        "247":  "6",
        "ESPN":  "9",
        "MADE":  "3",
        "EBY":  "2",
        "CONSENSUS":  "4.4",
        "INDUSTRY PRO":  "5",
        "EBY DIFF INDUSTRY":  "3"
    },
    {
        "TIER":  "2",
        "PLAYER":  "Tyran Stokes",
        "TEAM/HS":  "Ranier Beach ",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Wing Handler",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "1",
        "247":  "1",
        "ESPN":  "1",
        "MADE":  "1",
        "EBY":  "3",
        "CONSENSUS":  "1.4",
        "INDUSTRY PRO":  "1",
        "EBY DIFF INDUSTRY":  "-2"
    },
    {
        "TIER":  "3",
        "PLAYER":  "Hugo Yimga Mourkouri",
        "TEAM/HS":  "Nantarre 92 (FRA)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Scoring Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "14",
        "EBY":  "4",
        "CONSENSUS":  "9",
        "INDUSTRY PRO":  "14",
        "EBY DIFF INDUSTRY":  "-0.5"
    },
    {
        "TIER":  "3",
        "PLAYER":  "Caleb Holt ",
        "TEAM/HS":  "Prolific Prep ",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Scoring Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "9",
        "247":  "5",
        "ESPN":  "5",
        "MADE":  "8",
        "EBY":  "5",
        "CONSENSUS":  "6.4",
        "INDUSTRY PRO":  "6.75",
        "EBY DIFF INDUSTRY":  "1.75"
    },
    {
        "TIER":  "3",
        "PLAYER":  "Brandon McCoy",
        "TEAM/HS":  "Sierra Canyon ",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Combo Wing",
        "DEFENSIVE ROLE":  "Perimeter Disruptor",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "7",
        "247":  "9",
        "ESPN":  "19",
        "MADE":  "7",
        "EBY":  "6",
        "CONSENSUS":  "9.6",
        "INDUSTRY PRO":  "10.5",
        "EBY DIFF INDUSTRY":  "4.5"
    },
    {
        "TIER":  "3",
        "PLAYER":  "Cameron Williams ",
        "TEAM/HS":  "St. Mary\u0027s ",
        "COMMITMENT":  "Duke",
        "OFFENSIVE ROLE":  "Skilled Big ",
        "DEFENSIVE ROLE":  "Versatile Big",
        "HEIGHT":  "6\u002711\"",
        "RIVALS":  "14",
        "247":  "4",
        "ESPN":  "2",
        "MADE":  "9",
        "EBY":  "7",
        "CONSENSUS":  "7.2",
        "INDUSTRY PRO":  "7.25",
        "EBY DIFF INDUSTRY":  "0.25"
    },
    {
        "TIER":  "3",
        "PLAYER":  "Stefan Joksimovic",
        "TEAM/HS":  "Baskonia (SLO)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Wing Handler",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "8",
        "CONSENSUS":  "8",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "3",
        "PLAYER":  "Bryson Howard",
        "TEAM/HS":  "Heritage ",
        "COMMITMENT":  "Duke",
        "OFFENSIVE ROLE":  "Combo Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "3",
        "247":  "12",
        "ESPN":  "17",
        "MADE":  "5",
        "EBY":  "9",
        "CONSENSUS":  "9.2",
        "INDUSTRY PRO":  "9.25",
        "EBY DIFF INDUSTRY":  "0.25"
    },
    {
        "TIER":  "3",
        "PLAYER":  "Anthony Thompson",
        "TEAM/HS":  "Western Reserve Academy",
        "COMMITMENT":  "Ohio State",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "8",
        "247":  "7",
        "ESPN":  "12",
        "MADE":  "4",
        "EBY":  "10",
        "CONSENSUS":  "8.2",
        "INDUSTRY PRO":  "7.75",
        "EBY DIFF INDUSTRY":  "-2.25"
    },
    {
        "TIER":  "3",
        "PLAYER":  "Jordan Smith Jr. ",
        "TEAM/HS":  "St. Paul IV",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Slasher",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00272\"",
        "RIVALS":  "11",
        "247":  "2",
        "ESPN":  "3",
        "MADE":  "6",
        "EBY":  "11",
        "CONSENSUS":  "6.6",
        "INDUSTRY PRO":  "5.5",
        "EBY DIFF INDUSTRY":  "-5.5"
    },
    {
        "TIER":  "3",
        "PLAYER":  "Baba Olatodun",
        "TEAM/HS":  "James Hubert Blake ",
        "COMMITMENT":  "Maryland",
        "OFFENSIVE ROLE":  "Scoring Wing",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "10",
        "247":  "10",
        "ESPN":  "7",
        "MADE":  "13",
        "EBY":  "12",
        "CONSENSUS":  "10.4",
        "INDUSTRY PRO":  "10",
        "EBY DIFF INDUSTRY":  "-2"
    },
    {
        "TIER":  "4",
        "PLAYER":  "Christian Collins",
        "TEAM/HS":  "St. John Bosco ",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Play Finishing Forward",
        "DEFENSIVE ROLE":  "Versatile Big",
        "HEIGHT":  "6\u00279\"",
        "RIVALS":  "15",
        "247":  "8",
        "ESPN":  "8",
        "MADE":  "17",
        "EBY":  "13",
        "CONSENSUS":  "12.2",
        "INDUSTRY PRO":  "12",
        "EBY DIFF INDUSTRY":  "-1"
    },
    {
        "TIER":  "4",
        "PLAYER":  "Arafan Diane",
        "TEAM/HS":  "Iowa United Prep",
        "COMMITMENT":  "Houston",
        "OFFENSIVE ROLE":  "Post Scorer",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "7\u00271\"",
        "RIVALS":  "12",
        "247":  "17",
        "ESPN":  "20",
        "MADE":  "15",
        "EBY":  "14",
        "CONSENSUS":  "15.6",
        "INDUSTRY PRO":  "16",
        "EBY DIFF INDUSTRY":  "2"
    },
    {
        "TIER":  "4",
        "PLAYER":  "Deron Rippley Jr. ",
        "TEAM/HS":  "Blair Academy",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00271\"",
        "RIVALS":  "6",
        "247":  "6",
        "ESPN":  "16",
        "MADE":  "10",
        "EBY":  "15",
        "CONSENSUS":  "10.6",
        "INDUSTRY PRO":  "9.5",
        "EBY DIFF INDUSTRY":  "-5.5"
    },
    {
        "TIER":  "4",
        "PLAYER":  "Taylen Kinney",
        "TEAM/HS":  "Overtime Elite",
        "COMMITMENT":  "Kansas",
        "OFFENSIVE ROLE":  "Primary Initiator",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00272\"",
        "RIVALS":  "26",
        "247":  "13",
        "ESPN":  "18",
        "MADE":  "20",
        "EBY":  "16",
        "CONSENSUS":  "18.6",
        "INDUSTRY PRO":  "19.25",
        "EBY DIFF INDUSTRY":  "3.25"
    },
    {
        "TIER":  "4",
        "PLAYER":  "Qayden Samuels",
        "TEAM/HS":  "Bishop McNamara",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Scoring Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "43",
        "247":  "18",
        "ESPN":  "22",
        "MADE":  "36",
        "EBY":  "17",
        "CONSENSUS":  "27.2",
        "INDUSTRY PRO":  "29.75",
        "EBY DIFF INDUSTRY":  "12.75"
    },
    {
        "TIER":  "4",
        "PLAYER":  "Juom Maker Bol",
        "TEAM/HS":  "Baskonia (SSD)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Skilled Big ",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "7\u00271\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "18",
        "CONSENSUS":  "18",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "4",
        "PLAYER":  "Sayon Keita",
        "TEAM/HS":  "Barcelona (MLI)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "6\u002711\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "19",
        "EBY":  "19",
        "CONSENSUS":  "19",
        "INDUSTRY PRO":  "19",
        "EBY DIFF INDUSTRY":  "-14.25"
    },
    {
        "TIER":  "4",
        "PLAYER":  "Colben Landrew",
        "TEAM/HS":  "Wheeler",
        "COMMITMENT":  "UConn",
        "OFFENSIVE ROLE":  "Combo Wing",
        "DEFENSIVE ROLE":  "Perimeter Disruptor",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "25",
        "247":  "21",
        "ESPN":  "40",
        "MADE":  "18",
        "EBY":  "20",
        "CONSENSUS":  "24.8",
        "INDUSTRY PRO":  "26",
        "EBY DIFF INDUSTRY":  "6"
    },
    {
        "TIER":  "4",
        "PLAYER":  "Alex Constanza",
        "TEAM/HS":  "SPIRE Academy",
        "COMMITMENT":  "Georgetown",
        "OFFENSIVE ROLE":  "Scoring Wing",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "16",
        "247":  "22",
        "ESPN":  "28",
        "MADE":  "53",
        "EBY":  "21",
        "CONSENSUS":  "28",
        "INDUSTRY PRO":  "29.75",
        "EBY DIFF INDUSTRY":  "8.75"
    },
    {
        "TIER":  "4",
        "PLAYER":  "JJ Andrews",
        "TEAM/HS":  "Little Rock Christian ",
        "COMMITMENT":  "Arkansas",
        "OFFENSIVE ROLE":  "Slasher",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "29",
        "247":  "11",
        "ESPN":  "11",
        "MADE":  "16",
        "EBY":  "22",
        "CONSENSUS":  "17.8",
        "INDUSTRY PRO":  "16.75",
        "EBY DIFF INDUSTRY":  "-5.25"
    },
    {
        "TIER":  "4",
        "PLAYER":  "Jason Crowe Jr. ",
        "TEAM/HS":  "Inglewood ",
        "COMMITMENT":  "Missouri",
        "OFFENSIVE ROLE":  "Primary Initiator",
        "DEFENSIVE ROLE":  "Low Activity",
        "HEIGHT":  "6\u00272\"",
        "RIVALS":  "18",
        "247":  "3",
        "ESPN":  "4",
        "MADE":  "12",
        "EBY":  "23",
        "CONSENSUS":  "12",
        "INDUSTRY PRO":  "9.25",
        "EBY DIFF INDUSTRY":  "-13.75"
    },
    {
        "TIER":  "4",
        "PLAYER":  "Diego Niebla",
        "TEAM/HS":  "Joventut (ESP)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Chaser",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "24",
        "CONSENSUS":  "24",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "4",
        "PLAYER":  "Matthys Mahop",
        "TEAM/HS":  "INSEP (FRA)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00274\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "47",
        "EBY":  "25",
        "CONSENSUS":  "36",
        "INDUSTRY PRO":  "47",
        "EBY DIFF INDUSTRY":  "-13.25"
    },
    {
        "TIER":  "4",
        "PLAYER":  "Darius Ratliff",
        "TEAM/HS":  "Archbishop Stepanic",
        "COMMITMENT":  "USC",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "7\u00270\"",
        "RIVALS":  "13",
        "247":  "43",
        "ESPN":  "26",
        "MADE":  "27",
        "EBY":  "26",
        "CONSENSUS":  "27",
        "INDUSTRY PRO":  "27.25",
        "EBY DIFF INDUSTRY":  "1.25"
    },
    {
        "TIER":  "4",
        "PLAYER":  "Austin Goosby",
        "TEAM/HS":  "Dynamic Prep",
        "COMMITMENT":  "Texas",
        "OFFENSIVE ROLE":  "Combo Wing",
        "DEFENSIVE ROLE":  "Perimeter Disruptor",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "52",
        "247":  "19",
        "ESPN":  "23",
        "MADE":  "21",
        "EBY":  "27",
        "CONSENSUS":  "28.4",
        "INDUSTRY PRO":  "28.75",
        "EBY DIFF INDUSTRY":  "1.75"
    },
    {
        "TIER":  "4",
        "PLAYER":  "Toni Bryant",
        "TEAM/HS":  "Zephyrhills ",
        "COMMITMENT":  "Missouri",
        "OFFENSIVE ROLE":  "Play Finishing Forward",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "6\u002710\"",
        "RIVALS":  "39",
        "247":  "23",
        "ESPN":  "14",
        "MADE":  "49",
        "EBY":  "28",
        "CONSENSUS":  "30.6",
        "INDUSTRY PRO":  "31.25",
        "EBY DIFF INDUSTRY":  "3.25"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Junior County",
        "TEAM/HS":  "Wasatch Academy",
        "COMMITMENT":  "UConn",
        "OFFENSIVE ROLE":  "Combo Guard",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00274\"",
        "RIVALS":  "63",
        "247":  "29",
        "ESPN":  "37",
        "MADE":  "31",
        "EBY":  "29",
        "CONSENSUS":  "37.8",
        "INDUSTRY PRO":  "40",
        "EBY DIFF INDUSTRY":  "11"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Maximo Adams",
        "TEAM/HS":  "Sierra Canyon ",
        "COMMITMENT":  "UNC",
        "OFFENSIVE ROLE":  "Scoring Forward",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "19",
        "247":  "25",
        "ESPN":  "25",
        "MADE":  "23",
        "EBY":  "30",
        "CONSENSUS":  "24.4",
        "INDUSTRY PRO":  "23",
        "EBY DIFF INDUSTRY":  "-7"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Mathias Vazquez",
        "TEAM/HS":  "Overtime Elite (BRA)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Combo Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "46",
        "EBY":  "31",
        "CONSENSUS":  "38.5",
        "INDUSTRY PRO":  "46",
        "EBY DIFF INDUSTRY":  "-19.5"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Jaxon Richardson",
        "TEAM/HS":  "Southeastern Prep",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Slasher",
        "DEFENSIVE ROLE":  "Perimeter Disruptor",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "54",
        "247":  "20",
        "ESPN":  "15",
        "MADE":  "22",
        "EBY":  "32",
        "CONSENSUS":  "28.6",
        "INDUSTRY PRO":  "27.75",
        "EBY DIFF INDUSTRY":  "-4.25"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Caleb Gaskins",
        "TEAM/HS":  "Columbus ",
        "COMMITMENT":  "Miami",
        "OFFENSIVE ROLE":  "Slasher",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "5",
        "247":  "24",
        "ESPN":  "13",
        "MADE":  "11",
        "EBY":  "33",
        "CONSENSUS":  "17.2",
        "INDUSTRY PRO":  "13.25",
        "EBY DIFF INDUSTRY":  "-19.75"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Luca Foster",
        "TEAM/HS":  "Link Academy",
        "COMMITMENT":  "Gonzaga",
        "OFFENSIVE ROLE":  "Combo Wing",
        "DEFENSIVE ROLE":  "Chaser",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "46",
        "247":  "40",
        "ESPN":  "45",
        "MADE":  "50",
        "EBY":  "34",
        "CONSENSUS":  "43",
        "INDUSTRY PRO":  "45.25",
        "EBY DIFF INDUSTRY":  "11.25"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Miikka Muurinen",
        "TEAM/HS":  "Partizan (FIN)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u002711\"",
        "RIVALS":  "",
        "247":  "15",
        "ESPN":  "",
        "MADE":  "54",
        "EBY":  "35",
        "CONSENSUS":  "44.5",
        "INDUSTRY PRO":  "34.5",
        "EBY DIFF INDUSTRY":  "-17.75"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Cameron Houdino",
        "TEAM/HS":  "Cedevita Olimpija (FRA)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Versatile Big",
        "HEIGHT":  "6\u00279\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "44",
        "EBY":  "36",
        "CONSENSUS":  "40",
        "INDUSTRY PRO":  "44",
        "EBY DIFF INDUSTRY":  "-25"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Ilia Frolov",
        "TEAM/HS":  "Real Madrid (RUS)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Skilled Big ",
        "DEFENSIVE ROLE":  "Paint Prescence",
        "HEIGHT":  "6\u002710\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "37",
        "CONSENSUS":  "37",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "5",
        "PLAYER":  "Ethan Taylor",
        "TEAM/HS":  "Link Academy",
        "COMMITMENT":  "Michigan St.",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "7\u00271\"",
        "RIVALS":  "22",
        "247":  "28",
        "ESPN":  "44",
        "MADE":  "33",
        "EBY":  "38",
        "CONSENSUS":  "33",
        "INDUSTRY PRO":  "31.75",
        "EBY DIFF INDUSTRY":  "-6.25"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Bo Ogden",
        "TEAM/HS":  "Westlake",
        "COMMITMENT":  "Texas",
        "OFFENSIVE ROLE":  "Movement Shooter",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "37",
        "247":  "33",
        "ESPN":  "43",
        "MADE":  "41",
        "EBY":  "39",
        "CONSENSUS":  "38.6",
        "INDUSTRY PRO":  "38.5",
        "EBY DIFF INDUSTRY":  "-0.5"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Cole Cloer",
        "TEAM/HS":  "IMG Academy",
        "COMMITMENT":  "NC State",
        "OFFENSIVE ROLE":  "Movement Shooter",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "55",
        "247":  "27",
        "ESPN":  "24",
        "MADE":  "42",
        "EBY":  "40",
        "CONSENSUS":  "37.6",
        "INDUSTRY PRO":  "37",
        "EBY DIFF INDUSTRY":  "-3"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Miles Sadler",
        "TEAM/HS":  "Bella Vista Prep",
        "COMMITMENT":  "West Virginia",
        "OFFENSIVE ROLE":  "Primary Initiator",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "5\u002711\"",
        "RIVALS":  "24",
        "247":  "41",
        "ESPN":  "21",
        "MADE":  "25",
        "EBY":  "41",
        "CONSENSUS":  "30.4",
        "INDUSTRY PRO":  "27.75",
        "EBY DIFF INDUSTRY":  "-13.25"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Cameron Holmes",
        "TEAM/HS":  "Millenium",
        "COMMITMENT":  "Arizona",
        "OFFENSIVE ROLE":  "Scoring Wing",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "61",
        "247":  "30",
        "ESPN":  "38",
        "MADE":  "29",
        "EBY":  "42",
        "CONSENSUS":  "40",
        "INDUSTRY PRO":  "39.5",
        "EBY DIFF INDUSTRY":  "-2.5"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Tajh Ariza",
        "TEAM/HS":  "Link Academy",
        "COMMITMENT":  "Oregon",
        "OFFENSIVE ROLE":  "Slasher",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "20",
        "247":  "14",
        "ESPN":  "30",
        "MADE":  "24",
        "EBY":  "43",
        "CONSENSUS":  "26.2",
        "INDUSTRY PRO":  "22",
        "EBY DIFF INDUSTRY":  "-21"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Ralph Scott",
        "TEAM/HS":  "IMG Academy",
        "COMMITMENT":  "Tennessee",
        "OFFENSIVE ROLE":  "Play Finishing Forward",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "42",
        "247":  "35",
        "ESPN":  "54",
        "MADE":  "38",
        "EBY":  "44",
        "CONSENSUS":  "42.6",
        "INDUSTRY PRO":  "42.25",
        "EBY DIFF INDUSTRY":  "-1.75"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Davion Adkins",
        "TEAM/HS":  "Prolific Prep ",
        "COMMITMENT":  "Kansas",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Versatile Big",
        "HEIGHT":  "6\u00279\"",
        "RIVALS":  "28",
        "247":  "34",
        "ESPN":  "56",
        "MADE":  "28",
        "EBY":  "45",
        "CONSENSUS":  "38.2",
        "INDUSTRY PRO":  "36.5",
        "EBY DIFF INDUSTRY":  "-8.5"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Abdou Traore",
        "TEAM/HS":  "Notre Dame",
        "COMMITMENT":  "Arkansas",
        "OFFENSIVE ROLE":  "Scoring Guard",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00274\"",
        "RIVALS":  "30",
        "247":  "37",
        "ESPN":  "34",
        "MADE":  "34",
        "EBY":  "46",
        "CONSENSUS":  "36.2",
        "INDUSTRY PRO":  "33.75",
        "EBY DIFF INDUSTRY":  "-12.25"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Egor Amosov",
        "TEAM/HS":  "Real Madrid (RUS)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Connector Wing",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "47",
        "CONSENSUS":  "47",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "5",
        "PLAYER":  "Latrell Allmond",
        "TEAM/HS":  "Petersburg",
        "COMMITMENT":  "Oklahoma State",
        "OFFENSIVE ROLE":  "Post Scorer",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "32",
        "247":  "32",
        "ESPN":  "42",
        "MADE":  "30",
        "EBY":  "48",
        "CONSENSUS":  "36.8",
        "INDUSTRY PRO":  "34",
        "EBY DIFF INDUSTRY":  "-14"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Adonis Ratliff",
        "TEAM/HS":  "Archbishop Stepanic",
        "COMMITMENT":  "USC",
        "OFFENSIVE ROLE":  "Skilled Big ",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u002710\"",
        "RIVALS":  "17",
        "247":  "52",
        "ESPN":  "10",
        "MADE":  "31",
        "EBY":  "49",
        "CONSENSUS":  "31.8",
        "INDUSTRY PRO":  "27.5",
        "EBY DIFF INDUSTRY":  "-21.5"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Dakari Spear",
        "TEAM/HS":  "Dynamic Prep",
        "COMMITMENT":  "Texas Tech",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Perimeter Disruptor",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "85",
        "247":  "83",
        "ESPN":  "35",
        "MADE":  "103",
        "EBY":  "50",
        "CONSENSUS":  "71.2",
        "INDUSTRY PRO":  "76.5",
        "EBY DIFF INDUSTRY":  "26.5"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Quentin Coleman",
        "TEAM/HS":  "The Principia School",
        "COMMITMENT":  "Wake Forest",
        "OFFENSIVE ROLE":  "Combo Guard",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00274\"",
        "RIVALS":  "75",
        "247":  "92",
        "ESPN":  "125",
        "MADE":  "58",
        "EBY":  "51",
        "CONSENSUS":  "80.2",
        "INDUSTRY PRO":  "87.5",
        "EBY DIFF INDUSTRY":  "36.5"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Quincy Wadley ",
        "TEAM/HS":  "AZ Compass Prep",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Combo Wing",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "27",
        "247":  "55",
        "ESPN":  "55",
        "MADE":  "93",
        "EBY":  "52",
        "CONSENSUS":  "56.4",
        "INDUSTRY PRO":  "57.5",
        "EBY DIFF INDUSTRY":  "5.5"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Josh Irving",
        "TEAM/HS":  "Pasadena",
        "COMMITMENT":  "Texas A\u0026M",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "6\u002711\"",
        "RIVALS":  "41",
        "247":  "63",
        "ESPN":  "98",
        "MADE":  "43",
        "EBY":  "53",
        "CONSENSUS":  "59.6",
        "INDUSTRY PRO":  "61.25",
        "EBY DIFF INDUSTRY":  "8.25"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Jacob Webber",
        "TEAM/HS":  "La Lumiere",
        "COMMITMENT":  "Purdue",
        "OFFENSIVE ROLE":  "Movement Shooter",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "34",
        "247":  "73",
        "ESPN":  "99",
        "MADE":  "63",
        "EBY":  "54",
        "CONSENSUS":  "64.6",
        "INDUSTRY PRO":  "67.25",
        "EBY DIFF INDUSTRY":  "13.25"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Jasiah Jervis",
        "TEAM/HS":  "Archbishop Stepanic",
        "COMMITMENT":  "Michigan St.",
        "OFFENSIVE ROLE":  "Scoring Guard",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00274\"",
        "RIVALS":  "23",
        "247":  "39",
        "ESPN":  "31",
        "MADE":  "39",
        "EBY":  "55",
        "CONSENSUS":  "37.4",
        "INDUSTRY PRO":  "33",
        "EBY DIFF INDUSTRY":  "-22"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Luke Ertel",
        "TEAM/HS":  "Mt. Vernon",
        "COMMITMENT":  "Purdue",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00271\"",
        "RIVALS":  "53",
        "247":  "42",
        "ESPN":  "52",
        "MADE":  "109",
        "EBY":  "56",
        "CONSENSUS":  "62.4",
        "INDUSTRY PRO":  "64",
        "EBY DIFF INDUSTRY":  "8"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Ikenna Alozie",
        "TEAM/HS":  "Dream City Christian",
        "COMMITMENT":  "Houston",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00272\"",
        "RIVALS":  "36",
        "247":  "46",
        "ESPN":  "32",
        "MADE":  "79",
        "EBY":  "57",
        "CONSENSUS":  "50",
        "INDUSTRY PRO":  "48.25",
        "EBY DIFF INDUSTRY":  "-8.75"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Dovydas Buika",
        "TEAM/HS":  "Zalgris (LTU)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Combo Wing",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "51",
        "EBY":  "58",
        "CONSENSUS":  "54.5",
        "INDUSTRY PRO":  "51",
        "EBY DIFF INDUSTRY":  "-45.25"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Andrej Bjelic",
        "TEAM/HS":  "Real Madrid (SRB)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Combo Guard",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00274\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "59",
        "CONSENSUS":  "59",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "5",
        "PLAYER":  "Mate Khatiashvili",
        "TEAM/HS":  "Baskonia (GEO)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "Chaser",
        "HEIGHT":  "6\u00273\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "60",
        "CONSENSUS":  "60",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "5",
        "PLAYER":  "Nikola Karalic",
        "TEAM/HS":  "KK Mega (SRB)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Connector Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "61",
        "CONSENSUS":  "61",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "5",
        "PLAYER":  "Katrell Harmon",
        "TEAM/HS":  "Wasatch Academy",
        "COMMITMENT":  "Creighton",
        "OFFENSIVE ROLE":  "Combo Guard",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00273\"",
        "RIVALS":  "110",
        "247":  "58",
        "ESPN":  "59",
        "MADE":  "86",
        "EBY":  "62",
        "CONSENSUS":  "75",
        "INDUSTRY PRO":  "78.25",
        "EBY DIFF INDUSTRY":  "16.25"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Quinn Costello ",
        "TEAM/HS":  "Newman School",
        "COMMITMENT":  "Michigan",
        "OFFENSIVE ROLE":  "Skilled Big ",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00279\"",
        "RIVALS":  "33",
        "247":  "45",
        "ESPN":  "29",
        "MADE":  "72",
        "EBY":  "63",
        "CONSENSUS":  "48.4",
        "INDUSTRY PRO":  "44.75",
        "EBY DIFF INDUSTRY":  "-18.25"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Tristan Reed",
        "TEAM/HS":  "Link Academy",
        "COMMITMENT":  "Mississippi State",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "6\u00279\"",
        "RIVALS":  "69",
        "247":  "69",
        "ESPN":  "80",
        "MADE":  "56",
        "EBY":  "64",
        "CONSENSUS":  "67.6",
        "INDUSTRY PRO":  "68.5",
        "EBY DIFF INDUSTRY":  "4.5"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Klark Riethauser",
        "TEAM/HS":  "Chalon (SUI)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "91",
        "EBY":  "65",
        "CONSENSUS":  "65",
        "INDUSTRY PRO":  "91",
        "EBY DIFF INDUSTRY":  "-42.25"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Christopher Washington Jr.",
        "TEAM/HS":  "Providence Christian Aca.",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Play Finishing Forward",
        "DEFENSIVE ROLE":  "Perimeter Disruptor",
        "HEIGHT":  "6\u00279\"",
        "RIVALS":  "46",
        "247":  "31",
        "ESPN":  "59",
        "MADE":  "97",
        "EBY":  "66",
        "CONSENSUS":  "59.8",
        "INDUSTRY PRO":  "58.25",
        "EBY DIFF INDUSTRY":  "-7.75"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Anthony Felesi",
        "TEAM/HS":  "Utah Prep",
        "COMMITMENT":  "Pittsburg",
        "OFFENSIVE ROLE":  "Slasher",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "66",
        "247":  "49",
        "ESPN":  "58",
        "MADE":  "85",
        "EBY":  "67",
        "CONSENSUS":  "65",
        "INDUSTRY PRO":  "64.5",
        "EBY DIFF INDUSTRY":  "-2.5"
    },
    {
        "TIER":  "5",
        "PLAYER":  "Cheichk Niang",
        "TEAM/HS":  "Trento (ITA)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Play Finishing Forward",
        "DEFENSIVE ROLE":  "Perimeter Disruptor",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "68",
        "CONSENSUS":  "68",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "5",
        "PLAYER":  "Swann Penda",
        "TEAM/HS":  "Le Mans (FRA)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00279\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "69",
        "CONSENSUS":  "69",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "6",
        "PLAYER":  "Sam Funches",
        "TEAM/HS":  "Germantown",
        "COMMITMENT":  "Gonzaga",
        "OFFENSIVE ROLE":  "Skilled Big ",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "7\u00270\"",
        "RIVALS":  "48",
        "247":  "84",
        "ESPN":  "125",
        "MADE":  "108",
        "EBY":  "70",
        "CONSENSUS":  "87",
        "INDUSTRY PRO":  "91.25",
        "EBY DIFF INDUSTRY":  "21.25"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Kaden House",
        "TEAM/HS":  "AZ Compass Prep",
        "COMMITMENT":  "Maryland",
        "OFFENSIVE ROLE":  "Primary Initiator",
        "DEFENSIVE ROLE":  "Perimeter Disruptor",
        "HEIGHT":  "6\u00274\"",
        "RIVALS":  "56",
        "247":  "38",
        "ESPN":  "53",
        "MADE":  "148",
        "EBY":  "71",
        "CONSENSUS":  "73.2",
        "INDUSTRY PRO":  "73.75",
        "EBY DIFF INDUSTRY":  "2.75"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Joe Philon",
        "TEAM/HS":  "Monteverde",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Play Finishing Forward",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "50",
        "247":  "57",
        "ESPN":  "46",
        "MADE":  "48",
        "EBY":  "72",
        "CONSENSUS":  "54.6",
        "INDUSTRY PRO":  "50.25",
        "EBY DIFF INDUSTRY":  "-21.75"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Amadou Seini",
        "TEAM/HS":  "Bella Vista Prep (CMR)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "7\u00271\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "73",
        "CONSENSUS":  "73",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "6",
        "PLAYER":  "Fred Smith Jr.",
        "TEAM/HS":  "Briarcrest Christian",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Point Forward",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "107",
        "247":  "81",
        "ESPN":  "90",
        "MADE":  "84",
        "EBY":  "74",
        "CONSENSUS":  "87.2",
        "INDUSTRY PRO":  "90.5",
        "EBY DIFF INDUSTRY":  "16.5"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Sinan Huan",
        "TEAM/HS":  "Georgetown Prep",
        "COMMITMENT":  "Purdue",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "7\u00270\"",
        "RIVALS":  "38",
        "247":  "82",
        "ESPN":  "79",
        "MADE":  "96",
        "EBY":  "75",
        "CONSENSUS":  "74",
        "INDUSTRY PRO":  "73.75",
        "EBY DIFF INDUSTRY":  "-1.25"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Adam Oumiddoch",
        "TEAM/HS":  "Overtime Elite",
        "COMMITMENT":  "St. John\u0027s",
        "OFFENSIVE ROLE":  "Scoring Wing",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "57",
        "247":  "54",
        "ESPN":  "39",
        "MADE":  "57",
        "EBY":  "76",
        "CONSENSUS":  "56.6",
        "INDUSTRY PRO":  "51.75",
        "EBY DIFF INDUSTRY":  "-24.25"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Colin Rice ",
        "TEAM/HS":  "Waukee Northwest",
        "COMMITMENT":  "Nebraska",
        "OFFENSIVE ROLE":  "Movement Shooter",
        "DEFENSIVE ROLE":  "Chaser",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "71",
        "247":  "77",
        "ESPN":  "94",
        "MADE":  "67",
        "EBY":  "77",
        "CONSENSUS":  "77.2",
        "INDUSTRY PRO":  "77.25",
        "EBY DIFF INDUSTRY":  "0.25"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Marcus Johnson",
        "TEAM/HS":  "Garfield Heights",
        "COMMITMENT":  "South Carolina",
        "OFFENSIVE ROLE":  "Scoring Guard",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00272\"",
        "RIVALS":  "108",
        "247":  "36",
        "ESPN":  "41",
        "MADE":  "116",
        "EBY":  "78",
        "CONSENSUS":  "75.8",
        "INDUSTRY PRO":  "75.25",
        "EBY DIFF INDUSTRY":  "-2.75"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Collin Ross",
        "TEAM/HS":  "SPIRE Academy (Postgrad)",
        "COMMITMENT":  "VCU",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Versatile Big",
        "HEIGHT":  "6\u002710\"",
        "RIVALS":  "44",
        "247":  "131",
        "ESPN":  "150",
        "MADE":  "80",
        "EBY":  "79",
        "CONSENSUS":  "96.8",
        "INDUSTRY PRO":  "101.25",
        "EBY DIFF INDUSTRY":  "22.25"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Christian Gibson",
        "TEAM/HS":  "Tennessee Collegiate Academy",
        "COMMITMENT":  "UCF",
        "OFFENSIVE ROLE":  "Combo Guard",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "80",
        "247":  "76",
        "ESPN":  "67",
        "MADE":  "37",
        "EBY":  "80",
        "CONSENSUS":  "68",
        "INDUSTRY PRO":  "65",
        "EBY DIFF INDUSTRY":  "-15"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Aziz Olajuwon",
        "TEAM/HS":  "IMG Academy",
        "COMMITMENT":  "Stanford",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "78",
        "247":  "61",
        "ESPN":  "61",
        "MADE":  "66",
        "EBY":  "81",
        "CONSENSUS":  "69.4",
        "INDUSTRY PRO":  "66.5",
        "EBY DIFF INDUSTRY":  "-14.5"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Vaughn Karvala",
        "TEAM/HS":  "Bella Vista Prep",
        "COMMITMENT":  "Indiana",
        "OFFENSIVE ROLE":  "Scoring Wing",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "62",
        "247":  "47",
        "ESPN":  "36",
        "MADE":  "89",
        "EBY":  "82",
        "CONSENSUS":  "63.2",
        "INDUSTRY PRO":  "58.5",
        "EBY DIFF INDUSTRY":  "-23.5"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Herly Brutus",
        "TEAM/HS":  "Villages Charter",
        "COMMITMENT":  "LSU",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "86",
        "247":  "141",
        "ESPN":  "88",
        "MADE":  "105",
        "EBY":  "83",
        "CONSENSUS":  "100.6",
        "INDUSTRY PRO":  "105",
        "EBY DIFF INDUSTRY":  "22"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Ethan Harris",
        "TEAM/HS":  "Camas",
        "COMMITMENT":  "Iowa",
        "OFFENSIVE ROLE":  "Skilled Forward",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "73",
        "247":  "123",
        "ESPN":  "110",
        "MADE":  "71",
        "EBY":  "84",
        "CONSENSUS":  "92.2",
        "INDUSTRY PRO":  "94.25",
        "EBY DIFF INDUSTRY":  "10.25"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Sammy Jackson",
        "TEAM/HS":  "Roman Catholic",
        "COMMITMENT":  "VCU",
        "OFFENSIVE ROLE":  "Wing Handler",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "51",
        "247":  "62",
        "ESPN":  "72",
        "MADE":  "40",
        "EBY":  "85",
        "CONSENSUS":  "62",
        "INDUSTRY PRO":  "56.25",
        "EBY DIFF INDUSTRY":  "-28.75"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Jalen Montonati",
        "TEAM/HS":  "Owasso",
        "COMMITMENT":  "Oklahoma State",
        "OFFENSIVE ROLE":  "Movement Shooter",
        "DEFENSIVE ROLE":  "Chaser",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "70",
        "247":  "74",
        "ESPN":  "50",
        "MADE":  "92",
        "EBY":  "86",
        "CONSENSUS":  "74.4",
        "INDUSTRY PRO":  "71.5",
        "EBY DIFF INDUSTRY":  "-14.5"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Tarris Bouie",
        "TEAM/HS":  "SPIRE Academy",
        "COMMITMENT":  "Alabama",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "87",
        "247":  "51",
        "ESPN":  "33",
        "MADE":  "81",
        "EBY":  "87",
        "CONSENSUS":  "67.8",
        "INDUSTRY PRO":  "63",
        "EBY DIFF INDUSTRY":  "-24"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Carlos Medlock Jr.",
        "TEAM/HS":  "Link Academy",
        "COMMITMENT":  "Michigan St.",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "5\u002711\"",
        "RIVALS":  "68",
        "247":  "67",
        "ESPN":  "68",
        "MADE":  "73",
        "EBY":  "88",
        "CONSENSUS":  "72.8",
        "INDUSTRY PRO":  "69",
        "EBY DIFF INDUSTRY":  "-19"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Lucas Morillo",
        "TEAM/HS":  "Newman School",
        "COMMITMENT":  "Illinois",
        "OFFENSIVE ROLE":  "Combo Wing",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "21",
        "247":  "56",
        "ESPN":  "92",
        "MADE":  "59",
        "EBY":  "89",
        "CONSENSUS":  "63.4",
        "INDUSTRY PRO":  "57",
        "EBY DIFF INDUSTRY":  "-32"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Kayden Allen",
        "TEAM/HS":  "Long Island Lutheran",
        "COMMITMENT":  "Cincinnati",
        "OFFENSIVE ROLE":  "Scoring Guard",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "49",
        "247":  "48",
        "ESPN":  "75",
        "MADE":  "65",
        "EBY":  "90",
        "CONSENSUS":  "65.4",
        "INDUSTRY PRO":  "59.25",
        "EBY DIFF INDUSTRY":  "-30.75"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Elijah Williams",
        "TEAM/HS":  "TMI Episcopal",
        "COMMITMENT":  "Baylor",
        "OFFENSIVE ROLE":  "Scoring Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "60",
        "247":  "26",
        "ESPN":  "27",
        "MADE":  "55",
        "EBY":  "91",
        "CONSENSUS":  "51.8",
        "INDUSTRY PRO":  "42",
        "EBY DIFF INDUSTRY":  "-49"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Gage Mayfield",
        "TEAM/HS":  "Hale County",
        "COMMITMENT":  "Oklahoma",
        "OFFENSIVE ROLE":  "Play Finishing Forward",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "82",
        "247":  "60",
        "ESPN":  "69",
        "MADE":  "78",
        "EBY":  "92",
        "CONSENSUS":  "76.2",
        "INDUSTRY PRO":  "72.25",
        "EBY DIFF INDUSTRY":  "-19.75"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Chase Foster",
        "TEAM/HS":  "IMG Academy",
        "COMMITMENT":  "Pittsburg",
        "OFFENSIVE ROLE":  "Scoring Forward",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "40",
        "247":  "33",
        "ESPN":  "47",
        "MADE":  "69",
        "EBY":  "93",
        "CONSENSUS":  "56.4",
        "INDUSTRY PRO":  "47.25",
        "EBY DIFF INDUSTRY":  "-45.75"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Gavin Placide",
        "TEAM/HS":  "Family Faith Academy",
        "COMMITMENT":  "Wake Forest",
        "OFFENSIVE ROLE":  "Scoring Forward",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00279\"",
        "RIVALS":  "45",
        "247":  "50",
        "ESPN":  "60",
        "MADE":  "141",
        "EBY":  "94",
        "CONSENSUS":  "78",
        "INDUSTRY PRO":  "74",
        "EBY DIFF INDUSTRY":  "-20"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Louka Letailleur",
        "TEAM/HS":  "Gravelines (FRA)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Scoring Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "95",
        "CONSENSUS":  "95",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "6",
        "PLAYER":  "Yohance Connor",
        "TEAM/HS":  "Combine Academy/OTE",
        "COMMITMENT":  "Ole Miss",
        "OFFENSIVE ROLE":  "Combo Guard",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00272\"",
        "RIVALS":  "200",
        "247":  "105",
        "ESPN":  "200",
        "MADE":  "200",
        "EBY":  "96",
        "CONSENSUS":  "160.2",
        "INDUSTRY PRO":  "176.25",
        "EBY DIFF INDUSTRY":  "80.25"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Ognjen Srzentic",
        "TEAM/HS":  "KK Mega (SRB)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Wing Handler",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "76",
        "EBY":  "97",
        "CONSENSUS":  "86.5",
        "INDUSTRY PRO":  "76",
        "EBY DIFF INDUSTRY":  "-78"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Joe Sterling",
        "TEAM/HS":  "Harvard Westlake",
        "COMMITMENT":  "Texas",
        "OFFENSIVE ROLE":  "Combo Guard",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00273\"",
        "RIVALS":  "138",
        "247":  "107",
        "ESPN":  "100",
        "MADE":  "112",
        "EBY":  "98",
        "CONSENSUS":  "111",
        "INDUSTRY PRO":  "114.25",
        "EBY DIFF INDUSTRY":  "16.25"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Alex Egbuonu",
        "TEAM/HS":  "Lawrence Academy",
        "COMMITMENT":  "Marquette",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "106",
        "247":  "75",
        "ESPN":  "65",
        "MADE":  "200",
        "EBY":  "99",
        "CONSENSUS":  "109",
        "INDUSTRY PRO":  "111.5",
        "EBY DIFF INDUSTRY":  "12.5"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Ricards Aizpurs",
        "TEAM/HS":  "Stella Azzurra (LAT)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Combo Guard",
        "DEFENSIVE ROLE":  "Chaser",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "100",
        "CONSENSUS":  "20",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "6",
        "PLAYER":  "Maxime Meyer",
        "TEAM/HS":  "IMG Academy",
        "COMMITMENT":  "Duke",
        "OFFENSIVE ROLE":  "Connector Big",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "7\u00272\"",
        "RIVALS":  "77",
        "247":  "95",
        "ESPN":  "125",
        "MADE":  "99",
        "EBY":  "101",
        "CONSENSUS":  "99.4",
        "INDUSTRY PRO":  "99",
        "EBY DIFF INDUSTRY":  "-2"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Marcis Ponder",
        "TEAM/HS":  "Gilion Basketball Academy",
        "COMMITMENT":  "Florida St.",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "6\u002711\"",
        "RIVALS":  "47",
        "247":  "68",
        "ESPN":  "62",
        "MADE":  "107",
        "EBY":  "102",
        "CONSENSUS":  "77.2",
        "INDUSTRY PRO":  "71",
        "EBY DIFF INDUSTRY":  "-31"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Aleksandr Panasiuk",
        "TEAM/HS":  "Gran Canaria (RUS)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Combo Guard",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00274\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "103",
        "CONSENSUS":  "103",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "6",
        "PLAYER":  "Aiden Chronister",
        "TEAM/HS":  "The New School",
        "COMMITMENT":  "Missouri",
        "OFFENSIVE ROLE":  "Movement Shooter",
        "DEFENSIVE ROLE":  "Chaser",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "150",
        "247":  "71",
        "ESPN":  "89",
        "MADE":  "133",
        "EBY":  "104",
        "CONSENSUS":  "109.4",
        "INDUSTRY PRO":  "110.75",
        "EBY DIFF INDUSTRY":  "6.75"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Gallagher Placide",
        "TEAM/HS":  "Family Faith Academy",
        "COMMITMENT":  "Wake Forest",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "58",
        "247":  "78",
        "ESPN":  "125",
        "MADE":  "114",
        "EBY":  "105",
        "CONSENSUS":  "96",
        "INDUSTRY PRO":  "93.75",
        "EBY DIFF INDUSTRY":  "-11.25"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Aiden Derkack",
        "TEAM/HS":  "SPIRE Academy",
        "COMMITMENT":  "Providence",
        "OFFENSIVE ROLE":  "Slasher",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "121",
        "247":  "53",
        "ESPN":  "48",
        "MADE":  "70",
        "EBY":  "106",
        "CONSENSUS":  "79.6",
        "INDUSTRY PRO":  "73",
        "EBY DIFF INDUSTRY":  "-33"
    },
    {
        "TIER":  "6",
        "PLAYER":  "Adama Tambedou",
        "TEAM/HS":  "Putnam Science Academy",
        "COMMITMENT":  "Maryland",
        "OFFENSIVE ROLE":  "Slasher",
        "DEFENSIVE ROLE":  "Versatile Big",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "94",
        "247":  "122",
        "ESPN":  "150",
        "MADE":  "137",
        "EBY":  "107",
        "CONSENSUS":  "122",
        "INDUSTRY PRO":  "125.75",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "6",
        "PLAYER":  "Luke Barnett",
        "TEAM/HS":  "Mater Dei",
        "COMMITMENT":  "Kansas",
        "OFFENSIVE ROLE":  "Movement Shooter",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00273\"",
        "RIVALS":  "115",
        "247":  "144",
        "ESPN":  "125",
        "MADE":  "140",
        "EBY":  "108",
        "CONSENSUS":  "126.4",
        "INDUSTRY PRO":  "131",
        "EBY DIFF INDUSTRY":  "23"
    },
    {
        "TIER":  "7",
        "PLAYER":  "Endurance Aiyamenkhue",
        "TEAM/HS":  "Ratiopharm Ulm (NED)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "6\u002711\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "45",
        "EBY":  "109",
        "CONSENSUS":  "77",
        "INDUSTRY PRO":  "45",
        "EBY DIFF INDUSTRY":  "-97.75"
    },
    {
        "TIER":  "7",
        "PLAYER":  "Trey Pearson",
        "TEAM/HS":  "Pope John Paul II",
        "COMMITMENT":  "High Point",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00272\"",
        "RIVALS":  "125",
        "247":  "116",
        "ESPN":  "150",
        "MADE":  "106",
        "EBY":  "110",
        "CONSENSUS":  "121.4",
        "INDUSTRY PRO":  "124.25",
        "EBY DIFF INDUSTRY":  "14.25"
    },
    {
        "TIER":  "7",
        "PLAYER":  "Jacob Lanier",
        "TEAM/HS":  "Parkview Magnet",
        "COMMITMENT":  "Nebraska",
        "OFFENSIVE ROLE":  "Scoring Guard",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "127",
        "247":  "100",
        "ESPN":  "86",
        "MADE":  "200",
        "EBY":  "111",
        "CONSENSUS":  "124.8",
        "INDUSTRY PRO":  "128.25",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "7",
        "PLAYER":  "Darius Bivens",
        "TEAM/HS":  "Bishop O\u0027Connell",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00270\"",
        "RIVALS":  "99",
        "247":  "85",
        "ESPN":  "51",
        "MADE":  "101",
        "EBY":  "112",
        "CONSENSUS":  "89.6",
        "INDUSTRY PRO":  "84",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "7",
        "PLAYER":  "Patrick Hassan",
        "TEAM/HS":  "Trento (ITA)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Primary Initiator",
        "DEFENSIVE ROLE":  "???",
        "HEIGHT":  "6\u00272\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "113",
        "CONSENSUS":  "113",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "7",
        "PLAYER":  "Eli Sancomb",
        "TEAM/HS":  "Wheeling Central Catholic",
        "COMMITMENT":  "Liberty",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "135",
        "247":  "102",
        "ESPN":  "125",
        "MADE":  "119",
        "EBY":  "114",
        "CONSENSUS":  "119",
        "INDUSTRY PRO":  "120.25",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "7",
        "PLAYER":  "Shane Pendergrass",
        "TEAM/HS":  "Hargrave Military Academy (HS)",
        "COMMITMENT":  "George Mason",
        "OFFENSIVE ROLE":  "Play Finishing Forward",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "96",
        "247":  "142",
        "ESPN":  "150",
        "MADE":  "125",
        "EBY":  "115",
        "CONSENSUS":  "125.6",
        "INDUSTRY PRO":  "128.25",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "7",
        "PLAYER":  "Slim Rogers",
        "TEAM/HS":  "Centennial",
        "COMMITMENT":  "Stanford",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00272\"",
        "RIVALS":  "129",
        "247":  "103",
        "ESPN":  "125",
        "MADE":  "126",
        "EBY":  "116",
        "CONSENSUS":  "119.8",
        "INDUSTRY PRO":  "120.75",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "7",
        "PLAYER":  "Kaiden Bailey",
        "TEAM/HS":  "Santa Margarita Catholic",
        "COMMITMENT":  "Georgia Tech",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00272\"",
        "RIVALS":  "136",
        "247":  "117",
        "ESPN":  "125",
        "MADE":  "124",
        "EBY":  "117",
        "CONSENSUS":  "154.75",
        "INDUSTRY PRO":  "125.5",
        "EBY DIFF INDUSTRY":  "8.5"
    },
    {
        "TIER":  "7",
        "PLAYER":  "Moustapha Diop",
        "TEAM/HS":  "Overtime Elite",
        "COMMITMENT":  "Georgia Tech",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "6\u002710\"",
        "RIVALS":  "83",
        "247":  "97",
        "ESPN":  "125",
        "MADE":  "142",
        "EBY":  "118",
        "CONSENSUS":  "113",
        "INDUSTRY PRO":  "111.75",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "7",
        "PLAYER":  "Code Mbengue",
        "TEAM/HS":  "Gran Canaria (SEN)",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "6\u002711\"",
        "RIVALS":  "",
        "247":  "",
        "ESPN":  "",
        "MADE":  "",
        "EBY":  "119",
        "CONSENSUS":  "119",
        "INDUSTRY PRO":  "",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Jayden Hodge",
        "TEAM/HS":  "Monteverde",
        "COMMITMENT":  "Northwestern",
        "OFFENSIVE ROLE":  "Slasher",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "81",
        "247":  "64",
        "ESPN":  "81",
        "MADE":  "62",
        "EBY":  "",
        "CONSENSUS":  "72",
        "INDUSTRY PRO":  "72",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Ethan Mgbako",
        "TEAM/HS":  "Oak Hill Academy",
        "COMMITMENT":  "Vanderbilt",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "67",
        "247":  "65",
        "ESPN":  "93",
        "MADE":  "75",
        "EBY":  "",
        "CONSENSUS":  "75",
        "INDUSTRY PRO":  "75",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Jonathan Sanderson",
        "TEAM/HS":  "La Lumiere",
        "COMMITMENT":  "Notre Dame",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "Low Activity",
        "HEIGHT":  "6\u00272\"",
        "RIVALS":  "98",
        "247":  "66",
        "ESPN":  "66",
        "MADE":  "113",
        "EBY":  "",
        "CONSENSUS":  "85.75",
        "INDUSTRY PRO":  "85.75",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Anthony Brown",
        "TEAM/HS":  "Archbishop Carroll",
        "COMMITMENT":  "Vanderbilt",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00271\"",
        "RIVALS":  "145",
        "247":  "70",
        "ESPN":  "64",
        "MADE":  "74",
        "EBY":  "",
        "CONSENSUS":  "88.25",
        "INDUSTRY PRO":  "88.25",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Kevin Thomas",
        "TEAM/HS":  "Monteverde",
        "COMMITMENT":  "LSU",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "120",
        "247":  "72",
        "ESPN":  "71",
        "MADE":  "83",
        "EBY":  "",
        "CONSENSUS":  "86.5",
        "INDUSTRY PRO":  "86.5",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Dean Reuckert",
        "TEAM/HS":  "Timpview",
        "COMMITMENT":  "BYU",
        "OFFENSIVE ROLE":  "Movement Shooter",
        "DEFENSIVE ROLE":  "Low Activity",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "143",
        "247":  "79",
        "ESPN":  "73",
        "MADE":  "60",
        "EBY":  "",
        "CONSENSUS":  "88.75",
        "INDUSTRY PRO":  "88.75",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Collin Paul",
        "TEAM/HS":  "Calvary Christian Academy",
        "COMMITMENT":  "Florida St.",
        "OFFENSIVE ROLE":  "",
        "DEFENSIVE ROLE":  "",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "93",
        "247":  "86",
        "ESPN":  "125",
        "MADE":  "115",
        "EBY":  "",
        "CONSENSUS":  "104.75",
        "INDUSTRY PRO":  "104.75",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Neiko Mundey",
        "TEAM/HS":  "Prince George\u0027s Academy",
        "COMMITMENT":  "Texas A\u0026M",
        "OFFENSIVE ROLE":  "Primary Ball Handler",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00272\"",
        "RIVALS":  "88",
        "247":  "87",
        "ESPN":  "84",
        "MADE":  "52",
        "EBY":  "",
        "CONSENSUS":  "77.75",
        "INDUSTRY PRO":  "77.75",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Jalyn Collingwood",
        "TEAM/HS":  "Sidwell Friends",
        "COMMITMENT":  "Mississippi State",
        "OFFENSIVE ROLE":  "",
        "DEFENSIVE ROLE":  "",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "128",
        "247":  "88",
        "ESPN":  "150",
        "MADE":  "149",
        "EBY":  "",
        "CONSENSUS":  "128.75",
        "INDUSTRY PRO":  "128.75",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Josiah Johnson",
        "TEAM/HS":  "Mayfair",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "",
        "DEFENSIVE ROLE":  "",
        "HEIGHT":  "6\u00273\"",
        "RIVALS":  "122",
        "247":  "89",
        "ESPN":  "150",
        "MADE":  "94",
        "EBY":  "",
        "CONSENSUS":  "113.75",
        "INDUSTRY PRO":  "113.75",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Trey Beamer",
        "TEAM/HS":  "IMG Academy",
        "COMMITMENT":  "Boston College",
        "OFFENSIVE ROLE":  "Combo Guard",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00272\"",
        "RIVALS":  "104",
        "247":  "90",
        "ESPN":  "76",
        "MADE":  "200",
        "EBY":  "",
        "CONSENSUS":  "117.5",
        "INDUSTRY PRO":  "117.5",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Julius Avent",
        "TEAM/HS":  "Bergen Catholic",
        "COMMITMENT":  "Michigan St.",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Helper",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "79",
        "247":  "93",
        "ESPN":  "82",
        "MADE":  "64",
        "EBY":  "",
        "CONSENSUS":  "79.5",
        "INDUSTRY PRO":  "79.5",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Joseph Hartman",
        "TEAM/HS":  "The Rock School",
        "COMMITMENT":  "Michigan",
        "OFFENSIVE ROLE":  "Combo Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00276\"",
        "RIVALS":  "65",
        "247":  "94",
        "ESPN":  "87",
        "MADE":  "104",
        "EBY":  "",
        "CONSENSUS":  "87.5",
        "INDUSTRY PRO":  "87.5",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Jackson Kiss",
        "TEAM/HS":  "Utah Prep",
        "COMMITMENT":  "Iowa State",
        "OFFENSIVE ROLE":  "",
        "DEFENSIVE ROLE":  "",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "133",
        "247":  "95",
        "ESPN":  "125",
        "MADE":  "200",
        "EBY":  "",
        "CONSENSUS":  "138.25",
        "INDUSTRY PRO":  "138.25",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Jason Singleton",
        "TEAM/HS":  "Columbus Academy",
        "COMMITMENT":  "Harvard",
        "OFFENSIVE ROLE":  "",
        "DEFENSIVE ROLE":  "",
        "HEIGHT":  "6\u00274\"",
        "RIVALS":  "125",
        "247":  "104",
        "ESPN":  "125",
        "MADE":  "100",
        "EBY":  "",
        "CONSENSUS":  "113.5",
        "INDUSTRY PRO":  "113.5",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Willie Burnett III",
        "TEAM/HS":  "Gillion Academy",
        "COMMITMENT":  "Mississippi State",
        "OFFENSIVE ROLE":  "Combo Guard",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00274\"",
        "RIVALS":  "59",
        "247":  "109",
        "ESPN":  "77",
        "MADE":  "200",
        "EBY":  "",
        "CONSENSUS":  "111.25",
        "INDUSTRY PRO":  "111.25",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Jermal Jones Jr.",
        "TEAM/HS":  "Monteverde",
        "COMMITMENT":  "Pittsburg",
        "OFFENSIVE ROLE":  "Scoring Guard",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00273\"",
        "RIVALS":  "76",
        "247":  "110",
        "ESPN":  "83",
        "MADE":  "200",
        "EBY":  "",
        "CONSENSUS":  "117.25",
        "INDUSTRY PRO":  "117.25",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Chidi Nwigwe",
        "TEAM/HS":  "Wasatch Academy",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Slasher",
        "DEFENSIVE ROLE":  "Perimeter Disruptor",
        "HEIGHT":  "6\u00277\"",
        "RIVALS":  "103",
        "247":  "111",
        "ESPN":  "63",
        "MADE":  "200",
        "EBY":  "",
        "CONSENSUS":  "119.25",
        "INDUSTRY PRO":  "119.25",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Felipe Quinones",
        "TEAM/HS":  "Columbus",
        "COMMITMENT":  "Florida Atlantic",
        "OFFENSIVE ROLE":  "Combo Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "64",
        "247":  "118",
        "ESPN":  "74",
        "MADE":  "200",
        "EBY":  "",
        "CONSENSUS":  "114",
        "INDUSTRY PRO":  "114",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Christian Wiggins",
        "TEAM/HS":  "Wayzata",
        "COMMITMENT":  "Iowa State",
        "OFFENSIVE ROLE":  "",
        "DEFENSIVE ROLE":  "",
        "HEIGHT":  "6\u00273\"",
        "RIVALS":  "105",
        "247":  "119",
        "ESPN":  "150",
        "MADE":  "200",
        "EBY":  "",
        "CONSENSUS":  "143.5",
        "INDUSTRY PRO":  "143.5",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Trent Perry",
        "TEAM/HS":  "Link Academy",
        "COMMITMENT":  "Kansas",
        "OFFENSIVE ROLE":  "Off-Ball Wing",
        "DEFENSIVE ROLE":  "Perimeter Stopper",
        "HEIGHT":  "6\u00274\"",
        "RIVALS":  "142",
        "247":  "120",
        "ESPN":  "78",
        "MADE":  "102",
        "EBY":  "",
        "CONSENSUS":  "110.5",
        "INDUSTRY PRO":  "110.5",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Brandon Bass Jr.",
        "TEAM/HS":  "Windermere Prep",
        "COMMITMENT":  "Florida St.",
        "OFFENSIVE ROLE":  "",
        "DEFENSIVE ROLE":  "",
        "HEIGHT":  "6\u00274\"",
        "RIVALS":  "142",
        "247":  "120",
        "ESPN":  "78",
        "MADE":  "200",
        "EBY":  "",
        "CONSENSUS":  "135",
        "INDUSTRY PRO":  "135",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Cody Peck",
        "TEAM/HS":  "Davidson Day",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "",
        "DEFENSIVE ROLE":  "",
        "HEIGHT":  "6\u00279\"",
        "RIVALS":  "111",
        "247":  "125",
        "ESPN":  "125",
        "MADE":  "143",
        "EBY":  "",
        "CONSENSUS":  "126",
        "INDUSTRY PRO":  "126",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Preston Wade",
        "TEAM/HS":  "Academy of Central Florida",
        "COMMITMENT":  "?",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Rim Protector",
        "HEIGHT":  "6\u002710\"",
        "RIVALS":  "89",
        "247":  "136",
        "ESPN":  "91",
        "MADE":  "200",
        "EBY":  "",
        "CONSENSUS":  "129",
        "INDUSTRY PRO":  "129",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Jackson Sheffield ",
        "TEAM/HS":  "Hoover",
        "COMMITMENT":  "Vanderbilt",
        "OFFENSIVE ROLE":  "Play Finishing Big",
        "DEFENSIVE ROLE":  "Paint Prescence",
        "HEIGHT":  "6\u00279\"",
        "RIVALS":  "102",
        "247":  "138",
        "ESPN":  "95",
        "MADE":  "121",
        "EBY":  "",
        "CONSENSUS":  "114",
        "INDUSTRY PRO":  "114",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Alex Smith",
        "TEAM/HS":  "Prolific Prep",
        "COMMITMENT":  "Ohio State",
        "OFFENSIVE ROLE":  "",
        "DEFENSIVE ROLE":  "",
        "HEIGHT":  "6\u00278\"",
        "RIVALS":  "97",
        "247":  "140",
        "ESPN":  "125",
        "MADE":  "129",
        "EBY":  "",
        "CONSENSUS":  "122.75",
        "INDUSTRY PRO":  "122.75",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Kalek House",
        "TEAM/HS":  "AZ Compass Prep",
        "COMMITMENT":  "Xavier",
        "OFFENSIVE ROLE":  "Scoring Guard",
        "DEFENSIVE ROLE":  "Point-of-Attack",
        "HEIGHT":  "6\u00273\"",
        "RIVALS":  "109",
        "247":  "143",
        "ESPN":  "57",
        "MADE":  "139",
        "EBY":  "",
        "CONSENSUS":  "112",
        "INDUSTRY PRO":  "112",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Parker Robinson",
        "TEAM/HS":  "Overtime Elite",
        "COMMITMENT":  "Oklahoma State",
        "OFFENSIVE ROLE":  "",
        "DEFENSIVE ROLE":  "",
        "HEIGHT":  "6\u00275\"",
        "RIVALS":  "84",
        "247":  "145",
        "ESPN":  "150",
        "MADE":  "125",
        "EBY":  "",
        "CONSENSUS":  "126",
        "INDUSTRY PRO":  "126",
        "EBY DIFF INDUSTRY":  ""
    },
    {
        "TIER":  "",
        "PLAYER":  "Will Stevens",
        "TEAM/HS":  "Davidson Day",
        "COMMITMENT":  "Clemson",
        "OFFENSIVE ROLE":  "",
        "DEFENSIVE ROLE":  "",
        "HEIGHT":  "6\u00279\"",
        "RIVALS":  "92",
        "247":  "149",
        "ESPN":  "125",
        "MADE":  "68",
        "EBY":  "",
        "CONSENSUS":  "108.5",
        "INDUSTRY PRO":  "108.5",
        "EBY DIFF INDUSTRY":  null
    }
]
;
