const TEAM_COLORS = {
    // ACC
    "Duke": "#0069B0", // Duke Royal Blue (Lightened)
    "UNC": "#7BAFD4", // Carolina Blue
    "Miami": "#F47321", // Miami Orange (Better visibility than green)
    "Florida St.": "#782F40", // Garnet
    "Virginia": "#E57200", // Orange
    "Wake Forest": "#9E7E38", // Gold
    "Syracuse": "#F76900", // Orange
    "Pittsburgh": "#C1C6C8", // Silver/Grey (Blue is too dark?) - sticking to Gold #FFB81C
    "Pittsburg": "#FFB81C", // Pittsburgh Gold
    "Clemson": "#F56600", // Orange
    "Louisville": "#E03A3E", // Red
    "Notre Dame": "#C99700", // Gold
    "Georgia Tech": "#B3A369", // Tech Gold
    "Stanford": "#C41E3A", // Cardinal
    "Boston College": "#98002E", // Maroon (Might need lightening) -> #BC2045? Let's try standard.
    "Cal": "#FDB515", // Gold
    "SMU": "#CC0035", // Red

    // SEC
    "Kentucky": "#0033A0", // Royal Blue
    "Alabama": "#9E1B32", // Crimson
    "Auburn": "#E87722", // Orange
    "Arkansas": "#9D2235", // Cardinal
    "Tennessee": "#FF8200", // Orange
    "Florida": "#FA4616", // Orange
    "Texas": "#BF5700", // Burnt Orange
    "Oklahoma": "#841617", // Crimson
    "Texas A&M": "#500000", // Maroon
    "LSU": "#FDD023", // Purple and GOLD - Gold pops better
    "Missouri": "#F1B82D", // Gold
    "Ole Miss": "#CE1126",
    "Mississippi State": "#660000", // Maroon
    "South Carolina": "#73000A", // Garnet
    "Vanderbilt": "#A89968", // Gold

    // Big 12
    "Kansas": "#0051BA", // Blue
    "Baylor": "#154734", // Green - Warning: Dark. Maybe Gold #FFB81C?
    "Houston": "#C8102E", // Red
    "Arizona": "#CC0033", // Red
    "Iowa State": "#F1BE48", // Gold
    "Texas Tech": "#CC0000", // Red
    "West Virginia": "#EAAA00", // Gold
    "Cincinnati": "#E00122", // Red
    "BYU": "#002E5D", // Navy - Dark.
    "UCF": "#BA9B37", // Gold
    "Oklahoma State": "#FF7300", // Orange

    // Big Ten
    "Michigan St.": "#18453B", // Green
    "Michigan": "#FFCB05", // Maize
    "Purdue": "#CEB888", // Old Gold
    "Indiana": "#990000", // Crimson
    "Illinois": "#E84A27", // Orange
    "Ohio State": "#BB0000", // Scarlet
    "Maryland": "#E03A3E", // Red
    "Rutgers": "#CC0033", // Scarlet
    "UCLA": "#2D68C4", // Blue
    "USC": "#9D2235", // Cardinal
    "Oregon": "#154733", // Green
    "Washington": "#4B2E83", // Purple
    "Iowa": "#FFCD00", // Gold
    "Nebraska": "#E41C38", // Scarlet
    "Northwestern": "#4E2A84", // Purple

    // Big East
    "UConn": "#000E2F", // Navy
    "Marquette": "#FFCC00", // Gold
    "Villanova": "#0060A9", // Blue
    "Creighton": "#005CA9", // Blue
    "St. John's": "#BA0C2F", // Red
    "Providence": "#000000", // Black - Use White text? Or Silver #D6D6D6
    "Georgetown": "#041E42", // Gray #A7B1B7
    "Xavier": "#0C2340", // Navy
    "Seton Hall": "#0033A0", // Blue
    "Butler": "#13294B", // Blue
    "DePaul": "#005EB8", // Blue

    // Other
    "Gonzaga": "#041E42", // Navy
    "Memphis": "#003087", // Blue
    "San Diego St.": "#A6192E", // Red
    "UNLV": "#CF0A2C", // Red
    "St. Mary's": "#003262", // Navy
    "Dayton": "#CE1141", // Red
    "Florida Atlantic": "#003366", // Blue
    "VCU": "#FFB300", // Gold
    "Liberty": "#0A254E", // Navy
    "High Point": "#280071", // Purple
    "George Mason": "#006633", // Green
    "Harvard": "#A51C30", // Crimson
};

// Function to get color
function getTeamColor(teamName) {
    if (!teamName || teamName === '?' || teamName === '') return '#ffffff'; // Default to white

    // Direct match
    if (TEAM_COLORS[teamName]) return TEAM_COLORS[teamName];

    // Fallbacks for dark colors that might need lightening or unknown teams
    // Just return a generic 'accent' color or white if unknown
    return '#aebbc7'; // Default greyish
}
const TEAM_LOGOS = {
    // Manual Fixes for specific data strings
    "Mississippi State": "https://a.espncdn.com/i/teamlogos/ncaa/500/344.png",
    "Florida St.": "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png",
    "Pittsburgh": "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
    "Michigan St.": "https://a.espncdn.com/i/teamlogos/ncaa/500/127.png",
    "St. John's": "https://a.espncdn.com/i/teamlogos/ncaa/500/2599.png",
    "Oklahoma State": "https://a.espncdn.com/i/teamlogos/ncaa/500/197.png",
    "Texas A&M": "https://a.espncdn.com/i/teamlogos/ncaa/500/245.png",

    "UNF": "https://a.espncdn.com/i/teamlogos/ncaa/500/2454.png",
    "Oregon State Beavers": "https://a.espncdn.com/i/teamlogos/ncaa/500/204.png",
    "Arkansas State Red Wolves": "https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png",
    "FIU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2229.png",
    "UT Rio Grande Valley Vaqueros": "https://a.espncdn.com/i/teamlogos/ncaa/500/292.png",
    "Dayton Flyers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2168.png",
    "CLT": "https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png",
    "BING": "https://a.espncdn.com/i/teamlogos/ncaa/500/2066.png",
    "Golden Grizzlies": "https://a.espncdn.com/i/teamlogos/ncaa/500/2473.png",
    "Portland St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2502.png",
    "UGA": "https://a.espncdn.com/i/teamlogos/ncaa/500/61.png",
    "UVU": "https://a.espncdn.com/i/teamlogos/ncaa/500/3084.png",
    "Texas A&M Aggies": "https://a.espncdn.com/i/teamlogos/ncaa/500/245.png",
    "Northern Iowa": "https://a.espncdn.com/i/teamlogos/ncaa/500/2460.png",
    "High Point": "https://a.espncdn.com/i/teamlogos/ncaa/500/2272.png",
    "Troy Trojans": "https://a.espncdn.com/i/teamlogos/ncaa/500/2653.png",
    "NIA": "https://a.espncdn.com/i/teamlogos/ncaa/500/315.png",
    "MD Eastern": "https://a.espncdn.com/i/teamlogos/ncaa/500/2379.png",
    "South Florida Bulls": "https://a.espncdn.com/i/teamlogos/ncaa/500/58.png",
    "Niagara": "https://a.espncdn.com/i/teamlogos/ncaa/500/315.png",
    "Saint Peter's Peacocks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2612.png",
    "Tulsa": "https://a.espncdn.com/i/teamlogos/ncaa/500/202.png",
    "Memphis Tigers": "https://a.espncdn.com/i/teamlogos/ncaa/500/235.png",
    "Coppin State Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/2154.png",
    "Tribe": "https://a.espncdn.com/i/teamlogos/ncaa/500/2729.png",
    "Drexel Dragons": "https://a.espncdn.com/i/teamlogos/ncaa/500/2182.png",
    "California Golden Bears": "https://a.espncdn.com/i/teamlogos/ncaa/500/25.png",
    "Peacocks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2612.png",
    "Coastal": "https://a.espncdn.com/i/teamlogos/ncaa/500/324.png",
    "NC State": "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
    "Georgia Tech Yellow Jackets": "https://a.espncdn.com/i/teamlogos/ncaa/500/59.png",
    "Raiders": "https://a.espncdn.com/i/teamlogos/ncaa/500/2750.png",
    "LOU": "https://a.espncdn.com/i/teamlogos/ncaa/500/97.png",
    "La Salle": "https://a.espncdn.com/i/teamlogos/ncaa/500/2325.png",
    "NC A&T": "https://a.espncdn.com/i/teamlogos/ncaa/500/2448.png",
    "Santa Barbara": "https://a.espncdn.com/i/teamlogos/ncaa/500/2540.png",
    "LT": "https://a.espncdn.com/i/teamlogos/ncaa/500/2348.png",
    "SYR": "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
    "Wolfpack": "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
    "William & Mary": "https://a.espncdn.com/i/teamlogos/ncaa/500/2729.png",
    "Memphis": "https://a.espncdn.com/i/teamlogos/ncaa/500/235.png",
    "BOIS": "https://a.espncdn.com/i/teamlogos/ncaa/500/68.png",
    "COR": "https://a.espncdn.com/i/teamlogos/ncaa/500/172.png",
    "Florida St": "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png",
    "North Florida Ospreys": "https://a.espncdn.com/i/teamlogos/ncaa/500/2454.png",
    "CP": "https://a.espncdn.com/i/teamlogos/ncaa/500/13.png",
    "NHVN": "https://a.espncdn.com/i/teamlogos/ncaa/500/2441.png",
    "Portland Pilots": "https://a.espncdn.com/i/teamlogos/ncaa/500/2501.png",
    "San Diego Toreros": "https://a.espncdn.com/i/teamlogos/ncaa/500/301.png",
    "Mount St Marys": "https://a.espncdn.com/i/teamlogos/ncaa/500/116.png",
    "PROV": "https://a.espncdn.com/i/teamlogos/ncaa/500/2507.png",
    "Lions": "https://a.espncdn.com/i/teamlogos/ncaa/500/2545.png",
    "MAN": "https://a.espncdn.com/i/teamlogos/ncaa/500/2363.png",
    "New Mexico Lobos": "https://a.espncdn.com/i/teamlogos/ncaa/500/167.png",
    "SAC": "https://a.espncdn.com/i/teamlogos/ncaa/500/16.png",
    "UCF": "https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png",
    "PAC": "https://a.espncdn.com/i/teamlogos/ncaa/500/279.png",
    "TULN": "https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png",
    "Southern": "https://a.espncdn.com/i/teamlogos/ncaa/500/2582.png",
    "GASO": "https://a.espncdn.com/i/teamlogos/ncaa/500/290.png",
    "GB": "https://a.espncdn.com/i/teamlogos/ncaa/500/2739.png",
    "STO": "https://a.espncdn.com/i/teamlogos/ncaa/500/284.png",
    "Clemson Tigers": "https://a.espncdn.com/i/teamlogos/ncaa/500/228.png",
    "DEP": "https://a.espncdn.com/i/teamlogos/ncaa/500/305.png",
    "EWU": "https://a.espncdn.com/i/teamlogos/ncaa/500/331.png",
    "South Carolina": "https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png",
    "UNLV Rebels": "https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png",
    "Iona Gaels": "https://a.espncdn.com/i/teamlogos/ncaa/500/314.png",
    "APP": "https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png",
    "Buffalo Bulls": "https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png",
    "UMass Lowell River Hawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2349.png",
    "Old Dominion Monarchs": "https://a.espncdn.com/i/teamlogos/ncaa/500/295.png",
    "Marshall": "https://a.espncdn.com/i/teamlogos/ncaa/500/276.png",
    "Indiana St": "https://a.espncdn.com/i/teamlogos/ncaa/500/282.png",
    "SDST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2571.png",
    "Mercyhurst": "https://a.espncdn.com/i/teamlogos/ncaa/500/2385.png",
    "Penn": "https://a.espncdn.com/i/teamlogos/ncaa/500/219.png",
    "UIW": "https://a.espncdn.com/i/teamlogos/ncaa/500/2916.png",
    "Monarchs": "https://a.espncdn.com/i/teamlogos/ncaa/500/295.png",
    "Michigan State Spartans": "https://a.espncdn.com/i/teamlogos/ncaa/500/127.png",
    "Ospreys": "https://a.espncdn.com/i/teamlogos/ncaa/500/2454.png",
    "San José State Spartans": "https://a.espncdn.com/i/teamlogos/ncaa/500/23.png",
    "Saint Joseph's": "https://a.espncdn.com/i/teamlogos/ncaa/500/2603.png",
    "Rutgers Scarlet Knights": "https://a.espncdn.com/i/teamlogos/ncaa/500/164.png",
    "Pepperdine": "https://a.espncdn.com/i/teamlogos/ncaa/500/2492.png",
    "Kansas Jayhawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png",
    "Charleston": "https://a.espncdn.com/i/teamlogos/ncaa/500/232.png",
    "Pioneers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2529.png",
    "WKU": "https://a.espncdn.com/i/teamlogos/ncaa/500/98.png",
    "Pirates": "https://a.espncdn.com/i/teamlogos/ncaa/500/2550.png",
    "SAM": "https://a.espncdn.com/i/teamlogos/ncaa/500/2535.png",
    "Quinnipiac": "https://a.espncdn.com/i/teamlogos/ncaa/500/2514.png",
    "Grambling": "https://a.espncdn.com/i/teamlogos/ncaa/500/2755.png",
    "Keydets": "https://a.espncdn.com/i/teamlogos/ncaa/500/2678.png",
    "Orange": "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
    "Richmond": "https://a.espncdn.com/i/teamlogos/ncaa/500/257.png",
    "Northern Iowa Panthers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2460.png",
    "UAPB": "https://a.espncdn.com/i/teamlogos/ncaa/500/2029.png",
    "OU": "https://a.espncdn.com/i/teamlogos/ncaa/500/201.png",
    "Yellow Jackets": "https://a.espncdn.com/i/teamlogos/ncaa/500/59.png",
    "Chargers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2441.png",
    "Louisiana Tech Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2348.png",
    "Wildcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/2692.png",
    "Mississippi Valley State Delta Devils": "https://a.espncdn.com/i/teamlogos/ncaa/500/2400.png",
    "GA Southern": "https://a.espncdn.com/i/teamlogos/ncaa/500/290.png",
    "Drake": "https://a.espncdn.com/i/teamlogos/ncaa/500/2181.png",
    "BRAD": "https://a.espncdn.com/i/teamlogos/ncaa/500/71.png",
    "Cavaliers": "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
    "UTEP": "https://a.espncdn.com/i/teamlogos/ncaa/500/2638.png",
    "Dragons": "https://a.espncdn.com/i/teamlogos/ncaa/500/2182.png",
    "VCU Rams": "https://a.espncdn.com/i/teamlogos/ncaa/500/2670.png",
    "HAW": "https://a.espncdn.com/i/teamlogos/ncaa/500/62.png",
    "Fairleigh Dickinson Knights": "https://a.espncdn.com/i/teamlogos/ncaa/500/161.png",
    "Quakers": "https://a.espncdn.com/i/teamlogos/ncaa/500/219.png",
    "Houston": "https://a.espncdn.com/i/teamlogos/ncaa/500/248.png",
    "NAU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2464.png",
    "BUCK": "https://a.espncdn.com/i/teamlogos/ncaa/500/2083.png",
    "Saint Joseph's Hawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2603.png",
    "MRMK": "https://a.espncdn.com/i/teamlogos/ncaa/500/2771.png",
    "Presbyterian": "https://a.espncdn.com/i/teamlogos/ncaa/500/2506.png",
    "MOST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2623.png",
    "Dayton": "https://a.espncdn.com/i/teamlogos/ncaa/500/2168.png",
    "MASS": "https://a.espncdn.com/i/teamlogos/ncaa/500/113.png",
    "Maryland": "https://a.espncdn.com/i/teamlogos/ncaa/500/120.png",
    "Beach": "https://a.espncdn.com/i/teamlogos/ncaa/500/299.png",
    "Colgate": "https://a.espncdn.com/i/teamlogos/ncaa/500/2142.png",
    "Greyhounds": "https://a.espncdn.com/i/teamlogos/ncaa/500/2352.png",
    "Ohio Bobcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/195.png",
    "Northern Illinois Huskies": "https://a.espncdn.com/i/teamlogos/ncaa/500/2459.png",
    "Kent State Golden Flashes": "https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png",
    "COFC": "https://a.espncdn.com/i/teamlogos/ncaa/500/232.png",
    "Texas Tech Red Raiders": "https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png",
    "MVSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2400.png",
    "Sam Houston": "https://a.espncdn.com/i/teamlogos/ncaa/500/2534.png",
    "Florida State Seminoles": "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png",
    "Alabama A&M Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2010.png",
    "CHSO": "https://a.espncdn.com/i/teamlogos/ncaa/500/2127.png",
    "Texas St": "https://a.espncdn.com/i/teamlogos/ncaa/500/326.png",
    "Demons": "https://a.espncdn.com/i/teamlogos/ncaa/500/2466.png",
    "Lehigh Mountain Hawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2329.png",
    "SJU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2599.png",
    "Falcons": "https://a.espncdn.com/i/teamlogos/ncaa/500/189.png",
    "BU": "https://a.espncdn.com/i/teamlogos/ncaa/500/104.png",
    "Rhode Island": "https://a.espncdn.com/i/teamlogos/ncaa/500/227.png",
    "UTSA Roadrunners": "https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png",
    "Mountain Hawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2329.png",
    "Rice Owls": "https://a.espncdn.com/i/teamlogos/ncaa/500/242.png",
    "Fordham Rams": "https://a.espncdn.com/i/teamlogos/ncaa/500/2230.png",
    "TOL": "https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png",
    "VT": "https://a.espncdn.com/i/teamlogos/ncaa/500/259.png",
    "MILW": "https://a.espncdn.com/i/teamlogos/ncaa/500/270.png",
    "NCSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
    "Brown Bears": "https://a.espncdn.com/i/teamlogos/ncaa/500/225.png",
    "SBU": "https://a.espncdn.com/i/teamlogos/ncaa/500/179.png",
    "Wichita State Shockers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2724.png",
    "N Arizona": "https://a.espncdn.com/i/teamlogos/ncaa/500/2464.png",
    "Dons": "https://a.espncdn.com/i/teamlogos/ncaa/500/2539.png",
    "Grizzlies": "https://a.espncdn.com/i/teamlogos/ncaa/500/149.png",
    "Marshall Thundering Herd": "https://a.espncdn.com/i/teamlogos/ncaa/500/276.png",
    "TCU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png",
    "Mavericks": "https://a.espncdn.com/i/teamlogos/ncaa/500/250.png",
    "Rice": "https://a.espncdn.com/i/teamlogos/ncaa/500/242.png",
    "MISS": "https://a.espncdn.com/i/teamlogos/ncaa/500/145.png",
    "Providence": "https://a.espncdn.com/i/teamlogos/ncaa/500/2507.png",
    "Texas A&M-Corpus Christi Islanders": "https://a.espncdn.com/i/teamlogos/ncaa/500/357.png",
    "Bulls": "https://a.espncdn.com/i/teamlogos/ncaa/500/58.png",
    "Notre Dame": "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png",
    "Yale Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/43.png",
    "Little Rock Trojans": "https://a.espncdn.com/i/teamlogos/ncaa/500/2031.png",
    "UNM": "https://a.espncdn.com/i/teamlogos/ncaa/500/167.png",
    "UNT": "https://a.espncdn.com/i/teamlogos/ncaa/500/249.png",
    "Lopes": "https://a.espncdn.com/i/teamlogos/ncaa/500/2253.png",
    "Missouri": "https://a.espncdn.com/i/teamlogos/ncaa/500/142.png",
    "UT Martin": "https://a.espncdn.com/i/teamlogos/ncaa/500/2630.png",
    "ARK": "https://a.espncdn.com/i/teamlogos/ncaa/500/8.png",
    "PV": "https://a.espncdn.com/i/teamlogos/ncaa/500/2504.png",
    "AUB": "https://a.espncdn.com/i/teamlogos/ncaa/500/2.png",
    "Ohio": "https://a.espncdn.com/i/teamlogos/ncaa/500/195.png",
    "Pitt": "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
    "Towson": "https://a.espncdn.com/i/teamlogos/ncaa/500/119.png",
    "Air Force": "https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png",
    "Jackson St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2296.png",
    "Fairfield Stags": "https://a.espncdn.com/i/teamlogos/ncaa/500/2217.png",
    "Indiana": "https://a.espncdn.com/i/teamlogos/ncaa/500/84.png",
    "XAV": "https://a.espncdn.com/i/teamlogos/ncaa/500/2752.png",
    "WEB": "https://a.espncdn.com/i/teamlogos/ncaa/500/2692.png",
    "St Thomas (MN)": "https://a.espncdn.com/i/teamlogos/ncaa/500/2900.png",
    "SUU": "https://a.espncdn.com/i/teamlogos/ncaa/500/253.png",
    "Louisville Cardinals": "https://a.espncdn.com/i/teamlogos/ncaa/500/97.png",
    "Nebraska Cornhuskers": "https://a.espncdn.com/i/teamlogos/ncaa/500/158.png",
    "MINN": "https://a.espncdn.com/i/teamlogos/ncaa/500/135.png",
    "N Dakota St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png",
    "Denver": "https://a.espncdn.com/i/teamlogos/ncaa/500/2172.png",
    "Salukis": "https://a.espncdn.com/i/teamlogos/ncaa/500/79.png",
    "Mercer": "https://a.espncdn.com/i/teamlogos/ncaa/500/2382.png",
    "Santa Clara Broncos": "https://a.espncdn.com/i/teamlogos/ncaa/500/2541.png",
    "Massachusetts Minutemen": "https://a.espncdn.com/i/teamlogos/ncaa/500/113.png",
    "South Carolina State Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2569.png",
    "Chippewas": "https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png",
    "Navy Midshipmen": "https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png",
    "East Carolina": "https://a.espncdn.com/i/teamlogos/ncaa/500/151.png",
    "Washington": "https://a.espncdn.com/i/teamlogos/ncaa/500/264.png",
    "UNH": "https://a.espncdn.com/i/teamlogos/ncaa/500/160.png",
    "St. Bonaventure Bonnies": "https://a.espncdn.com/i/teamlogos/ncaa/500/179.png",
    "Michigan Wolverines": "https://a.espncdn.com/i/teamlogos/ncaa/500/130.png",
    "Sacred Heart": "https://a.espncdn.com/i/teamlogos/ncaa/500/2529.png",
    "Scarlet Knights": "https://a.espncdn.com/i/teamlogos/ncaa/500/164.png",
    "Long Island University Sharks": "https://a.espncdn.com/i/teamlogos/ncaa/500/112358.png",
    "ORU": "https://a.espncdn.com/i/teamlogos/ncaa/500/198.png",
    "SHSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2534.png",
    "CSUF": "https://a.espncdn.com/i/teamlogos/ncaa/500/2239.png",
    "RID": "https://a.espncdn.com/i/teamlogos/ncaa/500/2520.png",
    "W Carolina": "https://a.espncdn.com/i/teamlogos/ncaa/500/2717.png",
    "USU": "https://a.espncdn.com/i/teamlogos/ncaa/500/328.png",
    "Howard Bison": "https://a.espncdn.com/i/teamlogos/ncaa/500/47.png",
    "Lehigh": "https://a.espncdn.com/i/teamlogos/ncaa/500/2329.png",
    "Cornhuskers": "https://a.espncdn.com/i/teamlogos/ncaa/500/158.png",
    "North Carolina A&T Aggies": "https://a.espncdn.com/i/teamlogos/ncaa/500/2448.png",
    "Hou Christian": "https://a.espncdn.com/i/teamlogos/ncaa/500/2277.png",
    "UC Santa Barbara Gauchos": "https://a.espncdn.com/i/teamlogos/ncaa/500/2540.png",
    "VAL": "https://a.espncdn.com/i/teamlogos/ncaa/500/2674.png",
    "Bengals": "https://a.espncdn.com/i/teamlogos/ncaa/500/304.png",
    "HCU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2277.png",
    "UT Martin Skyhawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2630.png",
    "South Carolina Upstate Spartans": "https://a.espncdn.com/i/teamlogos/ncaa/500/2908.png",
    "Monmouth": "https://a.espncdn.com/i/teamlogos/ncaa/500/2405.png",
    "Kansas City": "https://a.espncdn.com/i/teamlogos/ncaa/500/140.png",
    "Alabama A&M": "https://a.espncdn.com/i/teamlogos/ncaa/500/2010.png",
    "SMU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png",
    "Idaho": "https://a.espncdn.com/i/teamlogos/ncaa/500/70.png",
    "DUQ": "https://a.espncdn.com/i/teamlogos/ncaa/500/2184.png",
    "Oklahoma Sooners": "https://a.espncdn.com/i/teamlogos/ncaa/500/201.png",
    "Northwestern State Demons": "https://a.espncdn.com/i/teamlogos/ncaa/500/2466.png",
    "DePaul": "https://a.espncdn.com/i/teamlogos/ncaa/500/305.png",
    "Utah Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/3101.png",
    "E Washington": "https://a.espncdn.com/i/teamlogos/ncaa/500/331.png",
    "Lakers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2385.png",
    "Golden Flashes": "https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png",
    "Oklahoma": "https://a.espncdn.com/i/teamlogos/ncaa/500/201.png",
    "Washington State Cougars": "https://a.espncdn.com/i/teamlogos/ncaa/500/265.png",
    "Illinois Fighting Illini": "https://a.espncdn.com/i/teamlogos/ncaa/500/356.png",
    "ORST": "https://a.espncdn.com/i/teamlogos/ncaa/500/204.png",
    "SFA": "https://a.espncdn.com/i/teamlogos/ncaa/500/2617.png",
    "Bonnies": "https://a.espncdn.com/i/teamlogos/ncaa/500/179.png",
    "Tarleton St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2627.png",
    "Manhattan Jaspers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2363.png",
    "Seahawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2681.png",
    "Kentucky": "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
    "Middle Tennessee Blue Raiders": "https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png",
    "Thundering Herd": "https://a.espncdn.com/i/teamlogos/ncaa/500/276.png",
    "Dukes": "https://a.espncdn.com/i/teamlogos/ncaa/500/256.png",
    "Northeastern Huskies": "https://a.espncdn.com/i/teamlogos/ncaa/500/111.png",
    "CBU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2856.png",
    "Siena Saints": "https://a.espncdn.com/i/teamlogos/ncaa/500/2561.png",
    "Roadrunners": "https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png",
    "Tennessee Volunteers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png",
    "River Hawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2349.png",
    "CIT": "https://a.espncdn.com/i/teamlogos/ncaa/500/2643.png",
    "UVA": "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
    "Northwestern Wildcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/77.png",
    "Vanderbilt": "https://a.espncdn.com/i/teamlogos/ncaa/500/238.png",
    "Panthers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2504.png",
    "Saint Francis": "https://a.espncdn.com/i/teamlogos/ncaa/500/2598.png",
    "La Salle Explorers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2325.png",
    "UNC Greensboro": "https://a.espncdn.com/i/teamlogos/ncaa/500/2430.png",
    "Elon Phoenix": "https://a.espncdn.com/i/teamlogos/ncaa/500/2210.png",
    "Jacksonville": "https://a.espncdn.com/i/teamlogos/ncaa/500/294.png",
    "LUC": "https://a.espncdn.com/i/teamlogos/ncaa/500/2350.png",
    "Navy": "https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png",
    "Cal State Bakersfield Roadrunners": "https://a.espncdn.com/i/teamlogos/ncaa/500/2934.png",
    "Missouri State Bears": "https://a.espncdn.com/i/teamlogos/ncaa/500/2623.png",
    "Manhattan": "https://a.espncdn.com/i/teamlogos/ncaa/500/2363.png",
    "Nebraska": "https://a.espncdn.com/i/teamlogos/ncaa/500/158.png",
    "CCSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2115.png",
    "Pacific": "https://a.espncdn.com/i/teamlogos/ncaa/500/279.png",
    "SC": "https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png",
    "CHST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2130.png",
    "Boston University Terriers": "https://a.espncdn.com/i/teamlogos/ncaa/500/104.png",
    "Purple Aces": "https://a.espncdn.com/i/teamlogos/ncaa/500/339.png",
    "GCU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2253.png",
    "WASH": "https://a.espncdn.com/i/teamlogos/ncaa/500/264.png",
    "Cowboys": "https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png",
    "Volunteers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png",
    "Tulane Green Wave": "https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png",
    "Oregon Ducks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png",
    "MRSH": "https://a.espncdn.com/i/teamlogos/ncaa/500/276.png",
    "Flames": "https://a.espncdn.com/i/teamlogos/ncaa/500/82.png",
    "Idaho State Bengals": "https://a.espncdn.com/i/teamlogos/ncaa/500/304.png",
    "UT Rio Grande": "https://a.espncdn.com/i/teamlogos/ncaa/500/292.png",
    "Binghamton Bearcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/2066.png",
    "Wofford Terriers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2747.png",
    "Mountaineers": "https://a.espncdn.com/i/teamlogos/ncaa/500/277.png",
    "Western Illinois Leathernecks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2710.png",
    "Long Island": "https://a.espncdn.com/i/teamlogos/ncaa/500/112358.png",
    "Stonehill": "https://a.espncdn.com/i/teamlogos/ncaa/500/284.png",
    "HPU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2272.png",
    "Great Danes": "https://a.espncdn.com/i/teamlogos/ncaa/500/399.png",
    "Boston College": "https://a.espncdn.com/i/teamlogos/ncaa/500/103.png",
    "Boston U": "https://a.espncdn.com/i/teamlogos/ncaa/500/104.png",
    "Morgan State Bears": "https://a.espncdn.com/i/teamlogos/ncaa/500/2415.png",
    "Gardner-Webb Runnin' Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2241.png",
    "Merrimack": "https://a.espncdn.com/i/teamlogos/ncaa/500/2771.png",
    "CA Baptist": "https://a.espncdn.com/i/teamlogos/ncaa/500/2856.png",
    "AR-Pine Bluff": "https://a.espncdn.com/i/teamlogos/ncaa/500/2029.png",
    "UC Riverside": "https://a.espncdn.com/i/teamlogos/ncaa/500/27.png",
    "SE Louisiana": "https://a.espncdn.com/i/teamlogos/ncaa/500/2545.png",
    "MICH": "https://a.espncdn.com/i/teamlogos/ncaa/500/130.png",
    "RedHawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2546.png",
    "Central Michigan Chippewas": "https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png",
    "UCI": "https://a.espncdn.com/i/teamlogos/ncaa/500/300.png",
    "Baylor Bears": "https://a.espncdn.com/i/teamlogos/ncaa/500/239.png",
    "IDST": "https://a.espncdn.com/i/teamlogos/ncaa/500/304.png",
    "Oakland": "https://a.espncdn.com/i/teamlogos/ncaa/500/2473.png",
    "IU Indianapolis Jaguars": "https://a.espncdn.com/i/teamlogos/ncaa/500/85.png",
    "San Diego State Aztecs": "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png",
    "Nicholls Colonels": "https://a.espncdn.com/i/teamlogos/ncaa/500/2447.png",
    "Hampton Pirates": "https://a.espncdn.com/i/teamlogos/ncaa/500/2261.png",
    "WMU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png",
    "Seton Hall": "https://a.espncdn.com/i/teamlogos/ncaa/500/2550.png",
    "ACU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2000.png",
    "Vandals": "https://a.espncdn.com/i/teamlogos/ncaa/500/70.png",
    "Texas State Bobcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/326.png",
    "Brown": "https://a.espncdn.com/i/teamlogos/ncaa/500/225.png",
    "MER": "https://a.espncdn.com/i/teamlogos/ncaa/500/2382.png",
    "Western KY": "https://a.espncdn.com/i/teamlogos/ncaa/500/98.png",
    "Washington St": "https://a.espncdn.com/i/teamlogos/ncaa/500/265.png",
    "Golden Bears": "https://a.espncdn.com/i/teamlogos/ncaa/500/25.png",
    "Thunderbirds": "https://a.espncdn.com/i/teamlogos/ncaa/500/253.png",
    "Illinois St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2287.png",
    "Delaware": "https://a.espncdn.com/i/teamlogos/ncaa/500/48.png",
    "UAlbany": "https://a.espncdn.com/i/teamlogos/ncaa/500/399.png",
    "Akron Zips": "https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png",
    "Coyotes": "https://a.espncdn.com/i/teamlogos/ncaa/500/233.png",
    "Bryant Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2803.png",
    "Toledo": "https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png",
    "Stony Brook Seawolves": "https://a.espncdn.com/i/teamlogos/ncaa/500/2619.png",
    "STBK": "https://a.espncdn.com/i/teamlogos/ncaa/500/2619.png",
    "Gators": "https://a.espncdn.com/i/teamlogos/ncaa/500/57.png",
    "Texas A&M-CC": "https://a.espncdn.com/i/teamlogos/ncaa/500/357.png",
    "Chanticleers": "https://a.espncdn.com/i/teamlogos/ncaa/500/324.png",
    "Big Green": "https://a.espncdn.com/i/teamlogos/ncaa/500/159.png",
    "Winthrop": "https://a.espncdn.com/i/teamlogos/ncaa/500/2737.png",
    "Kent State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png",
    "UConn": "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png",
    "UAlbany Great Danes": "https://a.espncdn.com/i/teamlogos/ncaa/500/399.png",
    "Bucknell Bison": "https://a.espncdn.com/i/teamlogos/ncaa/500/2083.png",
    "Miami (FL)": "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
    "BGSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/189.png",
    "Charlotte 49ers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png",
    "Bearcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png",
    "Tennessee Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/2635.png",
    "North Florida": "https://a.espncdn.com/i/teamlogos/ncaa/500/2454.png",
    "Patriots": "https://a.espncdn.com/i/teamlogos/ncaa/500/2244.png",
    "CLEM": "https://a.espncdn.com/i/teamlogos/ncaa/500/228.png",
    "FAU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png",
    "Florida Atlantic": "https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png",
    "Canisius": "https://a.espncdn.com/i/teamlogos/ncaa/500/2099.png",
    "Arizona Wildcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/12.png",
    "Evansville Purple Aces": "https://a.espncdn.com/i/teamlogos/ncaa/500/339.png",
    "Weber State Wildcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/2692.png",
    "Mocs": "https://a.espncdn.com/i/teamlogos/ncaa/500/236.png",
    "UT Arlington": "https://a.espncdn.com/i/teamlogos/ncaa/500/250.png",
    "Bruins": "https://a.espncdn.com/i/teamlogos/ncaa/500/26.png",
    "Saint Francis Red Flash": "https://a.espncdn.com/i/teamlogos/ncaa/500/2598.png",
    "Vanderbilt Commodores": "https://a.espncdn.com/i/teamlogos/ncaa/500/238.png",
    "Sharks": "https://a.espncdn.com/i/teamlogos/ncaa/500/112358.png",
    "Villanova": "https://a.espncdn.com/i/teamlogos/ncaa/500/222.png",
    "VCU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2670.png",
    "UMBC Retrievers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2378.png",
    "Delta Devils": "https://a.espncdn.com/i/teamlogos/ncaa/500/2400.png",
    "CSUB": "https://a.espncdn.com/i/teamlogos/ncaa/500/2934.png",
    "Belmont": "https://a.espncdn.com/i/teamlogos/ncaa/500/2057.png",
    "M-OH": "https://a.espncdn.com/i/teamlogos/ncaa/500/193.png",
    "COLO": "https://a.espncdn.com/i/teamlogos/ncaa/500/38.png",
    "Long Beach St": "https://a.espncdn.com/i/teamlogos/ncaa/500/299.png",
    "IU Indy": "https://a.espncdn.com/i/teamlogos/ncaa/500/85.png",
    "AAMU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2010.png",
    "Niagara Purple Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/315.png",
    "Louisiana": "https://a.espncdn.com/i/teamlogos/ncaa/500/309.png",
    "CSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/36.png",
    "Auburn Tigers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2.png",
    "Shockers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2724.png",
    "Hoyas": "https://a.espncdn.com/i/teamlogos/ncaa/500/46.png",
    "Milwaukee": "https://a.espncdn.com/i/teamlogos/ncaa/500/270.png",
    "OSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/194.png",
    "UND": "https://a.espncdn.com/i/teamlogos/ncaa/500/155.png",
    "Bearkats": "https://a.espncdn.com/i/teamlogos/ncaa/500/2534.png",
    "Lamar": "https://a.espncdn.com/i/teamlogos/ncaa/500/2320.png",
    "Virginia": "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
    "UNC Wilmington Seahawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/350.png",
    "MTST": "https://a.espncdn.com/i/teamlogos/ncaa/500/147.png",
    "Cal Poly Mustangs": "https://a.espncdn.com/i/teamlogos/ncaa/500/13.png",
    "Davidson Wildcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/2166.png",
    "ASU": "https://a.espncdn.com/i/teamlogos/ncaa/500/9.png",
    "Wofford": "https://a.espncdn.com/i/teamlogos/ncaa/500/2747.png",
    "Phoenix": "https://a.espncdn.com/i/teamlogos/ncaa/500/2739.png",
    "Omaha Mavericks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2437.png",
    "Evansville": "https://a.espncdn.com/i/teamlogos/ncaa/500/339.png",
    "Pilots": "https://a.espncdn.com/i/teamlogos/ncaa/500/2501.png",
    "Tarleton State Texans": "https://a.espncdn.com/i/teamlogos/ncaa/500/2627.png",
    "Michigan St": "https://a.espncdn.com/i/teamlogos/ncaa/500/127.png",
    "RGV": "https://a.espncdn.com/i/teamlogos/ncaa/500/292.png",
    "Midshipmen": "https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png",
    "UNC Asheville Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2427.png",
    "Utah Utes": "https://a.espncdn.com/i/teamlogos/ncaa/500/254.png",
    "The Citadel Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2643.png",
    "Blue Hens": "https://a.espncdn.com/i/teamlogos/ncaa/500/48.png",
    "SIUE": "https://a.espncdn.com/i/teamlogos/ncaa/500/2565.png",
    "Spiders": "https://a.espncdn.com/i/teamlogos/ncaa/500/257.png",
    "MARQ": "https://a.espncdn.com/i/teamlogos/ncaa/500/269.png",
    "Saint Louis": "https://a.espncdn.com/i/teamlogos/ncaa/500/139.png",
    "Sacred Heart Pioneers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2529.png",
    "Alabama": "https://a.espncdn.com/i/teamlogos/ncaa/500/333.png",
    "CLE": "https://a.espncdn.com/i/teamlogos/ncaa/500/325.png",
    "Maryland Terrapins": "https://a.espncdn.com/i/teamlogos/ncaa/500/120.png",
    "DREX": "https://a.espncdn.com/i/teamlogos/ncaa/500/2182.png",
    "Southern Illinois Salukis": "https://a.espncdn.com/i/teamlogos/ncaa/500/79.png",
    "TEX": "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
    "Crimson Tide": "https://a.espncdn.com/i/teamlogos/ncaa/500/333.png",
    "Utes": "https://a.espncdn.com/i/teamlogos/ncaa/500/254.png",
    "Texas": "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
    "DePaul Blue Demons": "https://a.espncdn.com/i/teamlogos/ncaa/500/305.png",
    "Loyola Marymount Lions": "https://a.espncdn.com/i/teamlogos/ncaa/500/2351.png",
    "Mean Green": "https://a.espncdn.com/i/teamlogos/ncaa/500/249.png",
    "SFPA": "https://a.espncdn.com/i/teamlogos/ncaa/500/2598.png",
    "Holy Cross Crusaders": "https://a.espncdn.com/i/teamlogos/ncaa/500/107.png",
    "Colgate Raiders": "https://a.espncdn.com/i/teamlogos/ncaa/500/2142.png",
    "Colonels": "https://a.espncdn.com/i/teamlogos/ncaa/500/2447.png",
    "North Alabama": "https://a.espncdn.com/i/teamlogos/ncaa/500/2453.png",
    "Cougars": "https://a.espncdn.com/i/teamlogos/ncaa/500/265.png",
    "American": "https://a.espncdn.com/i/teamlogos/ncaa/500/44.png",
    "SOU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2582.png",
    "Vaqueros": "https://a.espncdn.com/i/teamlogos/ncaa/500/292.png",
    "Presbyterian Blue Hose": "https://a.espncdn.com/i/teamlogos/ncaa/500/2506.png",
    "North Alabama Lions": "https://a.espncdn.com/i/teamlogos/ncaa/500/2453.png",
    "Samford Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2535.png",
    "UCD": "https://a.espncdn.com/i/teamlogos/ncaa/500/302.png",
    "Sacramento State Hornets": "https://a.espncdn.com/i/teamlogos/ncaa/500/16.png",
    "Lafayette Leopards": "https://a.espncdn.com/i/teamlogos/ncaa/500/322.png",
    "App State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png",
    "DEN": "https://a.espncdn.com/i/teamlogos/ncaa/500/2172.png",
    "Terriers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2747.png",
    "Kansas": "https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png",
    "Aztecs": "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png",
    "ALA": "https://a.espncdn.com/i/teamlogos/ncaa/500/333.png",
    "North Dakota": "https://a.espncdn.com/i/teamlogos/ncaa/500/155.png",
    "Western Carolina Catamounts": "https://a.espncdn.com/i/teamlogos/ncaa/500/2717.png",
    "OAK": "https://a.espncdn.com/i/teamlogos/ncaa/500/2473.png",
    "UNLV": "https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png",
    "Alcorn St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2016.png",
    "UNI": "https://a.espncdn.com/i/teamlogos/ncaa/500/2460.png",
    "HOW": "https://a.espncdn.com/i/teamlogos/ncaa/500/47.png",
    "Rattlers": "https://a.espncdn.com/i/teamlogos/ncaa/500/50.png",
    "APSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2046.png",
    "CMU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png",
    "E Illinois": "https://a.espncdn.com/i/teamlogos/ncaa/500/2197.png",
    "Liberty Flames": "https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png",
    "Delaware St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2169.png",
    "Stanford": "https://a.espncdn.com/i/teamlogos/ncaa/500/24.png",
    "Crimson": "https://a.espncdn.com/i/teamlogos/ncaa/500/108.png",
    "Northern Colorado Bears": "https://a.espncdn.com/i/teamlogos/ncaa/500/2458.png",
    "Utah Valley Wolverines": "https://a.espncdn.com/i/teamlogos/ncaa/500/3084.png",
    "UNC": "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
    "East Carolina Pirates": "https://a.espncdn.com/i/teamlogos/ncaa/500/151.png",
    "Huskies": "https://a.espncdn.com/i/teamlogos/ncaa/500/264.png",
    "NCCU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2428.png",
    "Columbia": "https://a.espncdn.com/i/teamlogos/ncaa/500/171.png",
    "BYU Cougars": "https://a.espncdn.com/i/teamlogos/ncaa/500/252.png",
    "Norfolk St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2450.png",
    "Murray St": "https://a.espncdn.com/i/teamlogos/ncaa/500/93.png",
    "PRES": "https://a.espncdn.com/i/teamlogos/ncaa/500/2506.png",
    "ILST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2287.png",
    "Jacksonville State Gamecocks": "https://a.espncdn.com/i/teamlogos/ncaa/500/55.png",
    "Seawolves": "https://a.espncdn.com/i/teamlogos/ncaa/500/2619.png",
    "WCU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2717.png",
    "BCU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2065.png",
    "Temple Owls": "https://a.espncdn.com/i/teamlogos/ncaa/500/218.png",
    "Campbell Fighting Camels": "https://a.espncdn.com/i/teamlogos/ncaa/500/2097.png",
    "Maryland Eastern Shore Hawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2379.png",
    "Little Rock": "https://a.espncdn.com/i/teamlogos/ncaa/500/2031.png",
    "Friars": "https://a.espncdn.com/i/teamlogos/ncaa/500/2507.png",
    "NWST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2466.png",
    "Stetson Hatters": "https://a.espncdn.com/i/teamlogos/ncaa/500/56.png",
    "JMU": "https://a.espncdn.com/i/teamlogos/ncaa/500/256.png",
    "Mississippi State Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/344.png",
    "Wolverines": "https://a.espncdn.com/i/teamlogos/ncaa/500/3084.png",
    "Eastern Illinois Panthers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2197.png",
    "UC Davis": "https://a.espncdn.com/i/teamlogos/ncaa/500/302.png",
    "Alabama St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2011.png",
    "BALL": "https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png",
    "St John's": "https://a.espncdn.com/i/teamlogos/ncaa/500/2599.png",
    "CCU": "https://a.espncdn.com/i/teamlogos/ncaa/500/324.png",
    "Pacific Tigers": "https://a.espncdn.com/i/teamlogos/ncaa/500/279.png",
    "Tennessee St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2634.png",
    "Blue Raiders": "https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png",
    "Long Beach State Beach": "https://a.espncdn.com/i/teamlogos/ncaa/500/299.png",
    "High Point Panthers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2272.png",
    "Louisiana Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/2348.png",
    "Cornell Big Red": "https://a.espncdn.com/i/teamlogos/ncaa/500/172.png",
    "S Illinois": "https://a.espncdn.com/i/teamlogos/ncaa/500/79.png",
    "DAY": "https://a.espncdn.com/i/teamlogos/ncaa/500/2168.png",
    "Weber St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2692.png",
    "ME": "https://a.espncdn.com/i/teamlogos/ncaa/500/311.png",
    "Alabama Crimson Tide": "https://a.espncdn.com/i/teamlogos/ncaa/500/333.png",
    "St. John's Red Storm": "https://a.espncdn.com/i/teamlogos/ncaa/500/2599.png",
    "Southern Jaguars": "https://a.espncdn.com/i/teamlogos/ncaa/500/2582.png",
    "UNC Greensboro Spartans": "https://a.espncdn.com/i/teamlogos/ncaa/500/2430.png",
    "Eastern Kentucky Colonels": "https://a.espncdn.com/i/teamlogos/ncaa/500/2198.png",
    "Rams": "https://a.espncdn.com/i/teamlogos/ncaa/500/2670.png",
    "Arkansas": "https://a.espncdn.com/i/teamlogos/ncaa/500/8.png",
    "Providence Friars": "https://a.espncdn.com/i/teamlogos/ncaa/500/2507.png",
    "Lamar Cardinals": "https://a.espncdn.com/i/teamlogos/ncaa/500/2320.png",
    "WICH": "https://a.espncdn.com/i/teamlogos/ncaa/500/2724.png",
    "Big Red": "https://a.espncdn.com/i/teamlogos/ncaa/500/172.png",
    "UCF Knights": "https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png",
    "TNTC": "https://a.espncdn.com/i/teamlogos/ncaa/500/2635.png",
    "Georgia Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/61.png",
    "UNCA": "https://a.espncdn.com/i/teamlogos/ncaa/500/2427.png",
    "Western Kentucky Hilltoppers": "https://a.espncdn.com/i/teamlogos/ncaa/500/98.png",
    "FSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png",
    "Black Bears": "https://a.espncdn.com/i/teamlogos/ncaa/500/311.png",
    "Radford": "https://a.espncdn.com/i/teamlogos/ncaa/500/2515.png",
    "Boise St": "https://a.espncdn.com/i/teamlogos/ncaa/500/68.png",
    "Georgia St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png",
    "Longwood Lancers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2344.png",
    "Rider": "https://a.espncdn.com/i/teamlogos/ncaa/500/2520.png",
    "N Kentucky": "https://a.espncdn.com/i/teamlogos/ncaa/500/94.png",
    "Flyers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2168.png",
    "Fullerton": "https://a.espncdn.com/i/teamlogos/ncaa/500/2239.png",
    "LSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/99.png",
    "Blue Devils": "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
    "JOES": "https://a.espncdn.com/i/teamlogos/ncaa/500/2603.png",
    "South Dakota Coyotes": "https://a.espncdn.com/i/teamlogos/ncaa/500/233.png",
    "Norfolk State Spartans": "https://a.espncdn.com/i/teamlogos/ncaa/500/2450.png",
    "Hawai'i Rainbow Warriors": "https://a.espncdn.com/i/teamlogos/ncaa/500/62.png",
    "Pittsburgh Panthers": "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
    "ND": "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png",
    "Texas Longhorns": "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
    "Duke Blue Devils": "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
    "Buccaneers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2193.png",
    "Saint Peter's": "https://a.espncdn.com/i/teamlogos/ncaa/500/2612.png",
    "SMU Mustangs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png",
    "LIU": "https://a.espncdn.com/i/teamlogos/ncaa/500/112358.png",
    "Morgan St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2415.png",
    "Duquesne Dukes": "https://a.espncdn.com/i/teamlogos/ncaa/500/2184.png",
    "Drexel": "https://a.espncdn.com/i/teamlogos/ncaa/500/2182.png",
    "INST": "https://a.espncdn.com/i/teamlogos/ncaa/500/282.png",
    "HALL": "https://a.espncdn.com/i/teamlogos/ncaa/500/2550.png",
    "Bobcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/326.png",
    "Iowa State": "https://a.espncdn.com/i/teamlogos/ncaa/500/66.png",
    "SCU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2541.png",
    "LAS": "https://a.espncdn.com/i/teamlogos/ncaa/500/2325.png",
    "IDHO": "https://a.espncdn.com/i/teamlogos/ncaa/500/70.png",
    "Yale": "https://a.espncdn.com/i/teamlogos/ncaa/500/43.png",
    "Redbirds": "https://a.espncdn.com/i/teamlogos/ncaa/500/2287.png",
    "Georgia": "https://a.espncdn.com/i/teamlogos/ncaa/500/61.png",
    "Hofstra": "https://a.espncdn.com/i/teamlogos/ncaa/500/2275.png",
    "Liberty": "https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png",
    "New Orleans": "https://a.espncdn.com/i/teamlogos/ncaa/500/2443.png",
    "MIZ": "https://a.espncdn.com/i/teamlogos/ncaa/500/142.png",
    "Bradley Braves": "https://a.espncdn.com/i/teamlogos/ncaa/500/71.png",
    "ETSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2193.png",
    "Seminoles": "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png",
    "Bisons": "https://a.espncdn.com/i/teamlogos/ncaa/500/288.png",
    "ETAM": "https://a.espncdn.com/i/teamlogos/ncaa/500/2837.png",
    "WVU": "https://a.espncdn.com/i/teamlogos/ncaa/500/277.png",
    "WAKE": "https://a.espncdn.com/i/teamlogos/ncaa/500/154.png",
    "East Texas A&M Lions": "https://a.espncdn.com/i/teamlogos/ncaa/500/2837.png",
    "Stetson": "https://a.espncdn.com/i/teamlogos/ncaa/500/56.png",
    "Drake Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2181.png",
    "MSST": "https://a.espncdn.com/i/teamlogos/ncaa/500/344.png",
    "ECU": "https://a.espncdn.com/i/teamlogos/ncaa/500/151.png",
    "CSU Northridge": "https://a.espncdn.com/i/teamlogos/ncaa/500/2463.png",
    "UC San Diego Tritons": "https://a.espncdn.com/i/teamlogos/ncaa/500/28.png",
    "Jax State": "https://a.espncdn.com/i/teamlogos/ncaa/500/55.png",
    "James Madison Dukes": "https://a.espncdn.com/i/teamlogos/ncaa/500/256.png",
    "GWEB": "https://a.espncdn.com/i/teamlogos/ncaa/500/2241.png",
    "Paladins": "https://a.espncdn.com/i/teamlogos/ncaa/500/231.png",
    "Georgetown Hoyas": "https://a.espncdn.com/i/teamlogos/ncaa/500/46.png",
    "LSU Tigers": "https://a.espncdn.com/i/teamlogos/ncaa/500/99.png",
    "Coppin St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2154.png",
    "Knights": "https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png",
    "Howard": "https://a.espncdn.com/i/teamlogos/ncaa/500/47.png",
    "W Illinois": "https://a.espncdn.com/i/teamlogos/ncaa/500/2710.png",
    "Norse": "https://a.espncdn.com/i/teamlogos/ncaa/500/94.png",
    "Utah State": "https://a.espncdn.com/i/teamlogos/ncaa/500/328.png",
    "TEM": "https://a.espncdn.com/i/teamlogos/ncaa/500/218.png",
    "UML": "https://a.espncdn.com/i/teamlogos/ncaa/500/2349.png",
    "Penn State Nittany Lions": "https://a.espncdn.com/i/teamlogos/ncaa/500/213.png",
    "GMU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2244.png",
    "Purdue Fort Wayne Mastodons": "https://a.espncdn.com/i/teamlogos/ncaa/500/2870.png",
    "Western Michigan Broncos": "https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png",
    "Maine": "https://a.espncdn.com/i/teamlogos/ncaa/500/311.png",
    "Oklahoma State Cowboys": "https://a.espncdn.com/i/teamlogos/ncaa/500/197.png",
    "Murray State Racers": "https://a.espncdn.com/i/teamlogos/ncaa/500/93.png",
    "Central Connecticut Blue Devils": "https://a.espncdn.com/i/teamlogos/ncaa/500/2115.png",
    "ORE": "https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png",
    "Jackson State Tigers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2296.png",
    "Seton Hall Pirates": "https://a.espncdn.com/i/teamlogos/ncaa/500/2550.png",
    "North Texas": "https://a.espncdn.com/i/teamlogos/ncaa/500/249.png",
    "Butler Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2086.png",
    "MSM": "https://a.espncdn.com/i/teamlogos/ncaa/500/116.png",
    "Spartans": "https://a.espncdn.com/i/teamlogos/ncaa/500/2430.png",
    "Explorers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2325.png",
    "Red Foxes": "https://a.espncdn.com/i/teamlogos/ncaa/500/2368.png",
    "Campbell": "https://a.espncdn.com/i/teamlogos/ncaa/500/2097.png",
    "SJSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/23.png",
    "MEM": "https://a.espncdn.com/i/teamlogos/ncaa/500/235.png",
    "Terrapins": "https://a.espncdn.com/i/teamlogos/ncaa/500/120.png",
    "N Colorado": "https://a.espncdn.com/i/teamlogos/ncaa/500/2458.png",
    "SIU Edwardsville Cougars": "https://a.espncdn.com/i/teamlogos/ncaa/500/2565.png",
    "AMER": "https://a.espncdn.com/i/teamlogos/ncaa/500/44.png",
    "Mercyhurst Lakers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2385.png",
    "Anteaters": "https://a.espncdn.com/i/teamlogos/ncaa/500/300.png",
    "Badgers": "https://a.espncdn.com/i/teamlogos/ncaa/500/275.png",
    "Matadors": "https://a.espncdn.com/i/teamlogos/ncaa/500/2463.png",
    "UNC Wilmington": "https://a.espncdn.com/i/teamlogos/ncaa/500/350.png",
    "STAN": "https://a.espncdn.com/i/teamlogos/ncaa/500/24.png",
    "Highlanders": "https://a.espncdn.com/i/teamlogos/ncaa/500/27.png",
    "NIU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2459.png",
    "Colonials": "https://a.espncdn.com/i/teamlogos/ncaa/500/2523.png",
    "USC Trojans": "https://a.espncdn.com/i/teamlogos/ncaa/500/30.png",
    "St Bonaventure": "https://a.espncdn.com/i/teamlogos/ncaa/500/179.png",
    "Omaha": "https://a.espncdn.com/i/teamlogos/ncaa/500/2437.png",
    "NE": "https://a.espncdn.com/i/teamlogos/ncaa/500/111.png",
    "Robert Morris": "https://a.espncdn.com/i/teamlogos/ncaa/500/2523.png",
    "UALB": "https://a.espncdn.com/i/teamlogos/ncaa/500/399.png",
    "George Washington Revolutionaries": "https://a.espncdn.com/i/teamlogos/ncaa/500/45.png",
    "San Diego": "https://a.espncdn.com/i/teamlogos/ncaa/500/301.png",
    "Cleveland State Vikings": "https://a.espncdn.com/i/teamlogos/ncaa/500/325.png",
    "JXST": "https://a.espncdn.com/i/teamlogos/ncaa/500/55.png",
    "Sun Devils": "https://a.espncdn.com/i/teamlogos/ncaa/500/9.png",
    "UCSB": "https://a.espncdn.com/i/teamlogos/ncaa/500/2540.png",
    "E Kentucky": "https://a.espncdn.com/i/teamlogos/ncaa/500/2198.png",
    "BRWN": "https://a.espncdn.com/i/teamlogos/ncaa/500/225.png",
    "Montana State Bobcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/147.png",
    "Kansas State Wildcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png",
    "Northeastern": "https://a.espncdn.com/i/teamlogos/ncaa/500/111.png",
    "Toledo Rockets": "https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png",
    "Le Moyne Dolphins": "https://a.espncdn.com/i/teamlogos/ncaa/500/2330.png",
    "Kennesaw State Owls": "https://a.espncdn.com/i/teamlogos/ncaa/500/338.png",
    "CAM": "https://a.espncdn.com/i/teamlogos/ncaa/500/2097.png",
    "Jaguars": "https://a.espncdn.com/i/teamlogos/ncaa/500/2582.png",
    "Hawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2603.png",
    "Youngstown St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2754.png",
    "WOF": "https://a.espncdn.com/i/teamlogos/ncaa/500/2747.png",
    "DART": "https://a.espncdn.com/i/teamlogos/ncaa/500/159.png",
    "VMI Keydets": "https://a.espncdn.com/i/teamlogos/ncaa/500/2678.png",
    "UNCG": "https://a.espncdn.com/i/teamlogos/ncaa/500/2430.png",
    "Creighton Bluejays": "https://a.espncdn.com/i/teamlogos/ncaa/500/156.png",
    "Oral Roberts": "https://a.espncdn.com/i/teamlogos/ncaa/500/198.png",
    "Trailblazers": "https://a.espncdn.com/i/teamlogos/ncaa/500/3101.png",
    "SELA": "https://a.espncdn.com/i/teamlogos/ncaa/500/2545.png",
    "EKU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2198.png",
    "RICH": "https://a.espncdn.com/i/teamlogos/ncaa/500/257.png",
    "Racers": "https://a.espncdn.com/i/teamlogos/ncaa/500/93.png",
    "Southeast Missouri State Redhawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2546.png",
    "Colorado St": "https://a.espncdn.com/i/teamlogos/ncaa/500/36.png",
    "Xavier Musketeers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2752.png",
    "Tennessee State Tigers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2634.png",
    "STET": "https://a.espncdn.com/i/teamlogos/ncaa/500/56.png",
    "Iowa": "https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png",
    "Cardinal": "https://a.espncdn.com/i/teamlogos/ncaa/500/24.png",
    "Sooners": "https://a.espncdn.com/i/teamlogos/ncaa/500/201.png",
    "Kansas City Roos": "https://a.espncdn.com/i/teamlogos/ncaa/500/140.png",
    "North Dakota Fighting Hawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/155.png",
    "Milwaukee Panthers": "https://a.espncdn.com/i/teamlogos/ncaa/500/270.png",
    "SDSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png",
    "KU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png",
    "MSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/127.png",
    "Kentucky Wildcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
    "Golden Lions": "https://a.espncdn.com/i/teamlogos/ncaa/500/2029.png",
    "NDSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png",
    "Pepperdine Waves": "https://a.espncdn.com/i/teamlogos/ncaa/500/2492.png",
    "Roos": "https://a.espncdn.com/i/teamlogos/ncaa/500/140.png",
    "South Dakota": "https://a.espncdn.com/i/teamlogos/ncaa/500/233.png",
    "Wright St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2750.png",
    "UNA": "https://a.espncdn.com/i/teamlogos/ncaa/500/2453.png",
    "AMCC": "https://a.espncdn.com/i/teamlogos/ncaa/500/357.png",
    "Akron": "https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png",
    "Rutgers": "https://a.espncdn.com/i/teamlogos/ncaa/500/164.png",
    "Red Raiders": "https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png",
    "Bethune-Cookman Wildcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/2065.png",
    "Troy": "https://a.espncdn.com/i/teamlogos/ncaa/500/2653.png",
    "UCSD": "https://a.espncdn.com/i/teamlogos/ncaa/500/28.png",
    "Furman Paladins": "https://a.espncdn.com/i/teamlogos/ncaa/500/231.png",
    "GW": "https://a.espncdn.com/i/teamlogos/ncaa/500/45.png",
    "Longwood": "https://a.espncdn.com/i/teamlogos/ncaa/500/2344.png",
    "South Alabama Jaguars": "https://a.espncdn.com/i/teamlogos/ncaa/500/6.png",
    "Princeton Tigers": "https://a.espncdn.com/i/teamlogos/ncaa/500/163.png",
    "WYO": "https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png",
    "Boise State Broncos": "https://a.espncdn.com/i/teamlogos/ncaa/500/68.png",
    "JAX": "https://a.espncdn.com/i/teamlogos/ncaa/500/294.png",
    "Cardinals": "https://a.espncdn.com/i/teamlogos/ncaa/500/97.png",
    "Butler": "https://a.espncdn.com/i/teamlogos/ncaa/500/2086.png",
    "OKST": "https://a.espncdn.com/i/teamlogos/ncaa/500/197.png",
    "Florida Gators": "https://a.espncdn.com/i/teamlogos/ncaa/500/57.png",
    "Mississippi St": "https://a.espncdn.com/i/teamlogos/ncaa/500/344.png",
    "Illinois State Redbirds": "https://a.espncdn.com/i/teamlogos/ncaa/500/2287.png",
    "VAN": "https://a.espncdn.com/i/teamlogos/ncaa/500/238.png",
    "UNCW": "https://a.espncdn.com/i/teamlogos/ncaa/500/350.png",
    "Eastern Washington Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/331.png",
    "CSUN": "https://a.espncdn.com/i/teamlogos/ncaa/500/2463.png",
    "Purdue": "https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png",
    "BUT": "https://a.espncdn.com/i/teamlogos/ncaa/500/2086.png",
    "Florida Atlantic Owls": "https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png",
    "Texas Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png",
    "TXSO": "https://a.espncdn.com/i/teamlogos/ncaa/500/2640.png",
    "Florida A&M Rattlers": "https://a.espncdn.com/i/teamlogos/ncaa/500/50.png",
    "OMA": "https://a.espncdn.com/i/teamlogos/ncaa/500/2437.png",
    "Rebels": "https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png",
    "Zips": "https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png",
    "C Connecticut": "https://a.espncdn.com/i/teamlogos/ncaa/500/2115.png",
    "HARV": "https://a.espncdn.com/i/teamlogos/ncaa/500/108.png",
    "RMU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2523.png",
    "BC": "https://a.espncdn.com/i/teamlogos/ncaa/500/103.png",
    "COLU": "https://a.espncdn.com/i/teamlogos/ncaa/500/171.png",
    "FUR": "https://a.espncdn.com/i/teamlogos/ncaa/500/231.png",
    "DETM": "https://a.espncdn.com/i/teamlogos/ncaa/500/2174.png",
    "SLU": "https://a.espncdn.com/i/teamlogos/ncaa/500/139.png",
    "Louisiana Ragin' Cajuns": "https://a.espncdn.com/i/teamlogos/ncaa/500/309.png",
    "New Hampshire Wildcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/160.png",
    "TOW": "https://a.espncdn.com/i/teamlogos/ncaa/500/119.png",
    "Maine Black Bears": "https://a.espncdn.com/i/teamlogos/ncaa/500/311.png",
    "HOU": "https://a.espncdn.com/i/teamlogos/ncaa/500/248.png",
    "LONG": "https://a.espncdn.com/i/teamlogos/ncaa/500/2344.png",
    "FRES": "https://a.espncdn.com/i/teamlogos/ncaa/500/278.png",
    "Prairie View A&M Panthers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2504.png",
    "Fighting Irish": "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png",
    "Hawkeyes": "https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png",
    "NJIT Highlanders": "https://a.espncdn.com/i/teamlogos/ncaa/500/2885.png",
    "SEMO": "https://a.espncdn.com/i/teamlogos/ncaa/500/2546.png",
    "Musketeers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2752.png",
    "Cal Poly": "https://a.espncdn.com/i/teamlogos/ncaa/500/13.png",
    "Bethune": "https://a.espncdn.com/i/teamlogos/ncaa/500/2065.png",
    "Central Arkansas Bears": "https://a.espncdn.com/i/teamlogos/ncaa/500/2110.png",
    "SE Missouri": "https://a.espncdn.com/i/teamlogos/ncaa/500/2546.png",
    "CAL": "https://a.espncdn.com/i/teamlogos/ncaa/500/25.png",
    "Siena": "https://a.espncdn.com/i/teamlogos/ncaa/500/2561.png",
    "Detroit Mercy": "https://a.espncdn.com/i/teamlogos/ncaa/500/2174.png",
    "UK": "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
    "Ohio State": "https://a.espncdn.com/i/teamlogos/ncaa/500/194.png",
    "Leathernecks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2710.png",
    "Oregon St": "https://a.espncdn.com/i/teamlogos/ncaa/500/204.png",
    "Leopards": "https://a.espncdn.com/i/teamlogos/ncaa/500/322.png",
    "PUR": "https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png",
    "Stags": "https://a.espncdn.com/i/teamlogos/ncaa/500/2217.png",
    "UPST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2908.png",
    "Waves": "https://a.espncdn.com/i/teamlogos/ncaa/500/2492.png",
    "PFW": "https://a.espncdn.com/i/teamlogos/ncaa/500/2870.png",
    "Florida": "https://a.espncdn.com/i/teamlogos/ncaa/500/57.png",
    "Austin Peay Governors": "https://a.espncdn.com/i/teamlogos/ncaa/500/2046.png",
    "Southern Utah": "https://a.espncdn.com/i/teamlogos/ncaa/500/253.png",
    "N'Western St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2466.png",
    "G Washington": "https://a.espncdn.com/i/teamlogos/ncaa/500/45.png",
    "URI": "https://a.espncdn.com/i/teamlogos/ncaa/500/227.png",
    "Loyola Chicago": "https://a.espncdn.com/i/teamlogos/ncaa/500/2350.png",
    "Beavers": "https://a.espncdn.com/i/teamlogos/ncaa/500/204.png",
    "Detroit Mercy Titans": "https://a.espncdn.com/i/teamlogos/ncaa/500/2174.png",
    "Georgia State Panthers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png",
    "SCST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2569.png",
    "AF": "https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png",
    "Marist Red Foxes": "https://a.espncdn.com/i/teamlogos/ncaa/500/2368.png",
    "Seattle U Redhawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2547.png",
    "COPP": "https://a.espncdn.com/i/teamlogos/ncaa/500/2154.png",
    "Utah": "https://a.espncdn.com/i/teamlogos/ncaa/500/254.png",
    "San Francisco Dons": "https://a.espncdn.com/i/teamlogos/ncaa/500/2539.png",
    "McNeese Cowboys": "https://a.espncdn.com/i/teamlogos/ncaa/500/2377.png",
    "USC": "https://a.espncdn.com/i/teamlogos/ncaa/500/30.png",
    "VILL": "https://a.espncdn.com/i/teamlogos/ncaa/500/222.png",
    "LIB": "https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png",
    "Grambling Tigers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2755.png",
    "NU": "https://a.espncdn.com/i/teamlogos/ncaa/500/77.png",
    "Nevada": "https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png",
    "Utah Tech Trailblazers": "https://a.espncdn.com/i/teamlogos/ncaa/500/3101.png",
    "Sam Houston Bearkats": "https://a.espncdn.com/i/teamlogos/ncaa/500/2534.png",
    "Catamounts": "https://a.espncdn.com/i/teamlogos/ncaa/500/2717.png",
    "SC State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2569.png",
    "Retrievers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2378.png",
    "UC Irvine Anteaters": "https://a.espncdn.com/i/teamlogos/ncaa/500/300.png",
    "Golden Hurricane": "https://a.espncdn.com/i/teamlogos/ncaa/500/202.png",
    "UAB": "https://a.espncdn.com/i/teamlogos/ncaa/500/5.png",
    "UC Riverside Highlanders": "https://a.espncdn.com/i/teamlogos/ncaa/500/27.png",
    "Fighting Illini": "https://a.espncdn.com/i/teamlogos/ncaa/500/356.png",
    "Cincinnati": "https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png",
    "Tulane": "https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png",
    "Vikings": "https://a.espncdn.com/i/teamlogos/ncaa/500/2502.png",
    "GRAM": "https://a.espncdn.com/i/teamlogos/ncaa/500/2755.png",
    "Warhawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png",
    "Ball State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png",
    "Hawai'i": "https://a.espncdn.com/i/teamlogos/ncaa/500/62.png",
    "Titans": "https://a.espncdn.com/i/teamlogos/ncaa/500/2174.png",
    "Jaspers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2363.png",
    "UVM": "https://a.espncdn.com/i/teamlogos/ncaa/500/261.png",
    "Fighting Camels": "https://a.espncdn.com/i/teamlogos/ncaa/500/2097.png",
    "Missouri Tigers": "https://a.espncdn.com/i/teamlogos/ncaa/500/142.png",
    "USA": "https://a.espncdn.com/i/teamlogos/ncaa/500/6.png",
    "UTSA": "https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png",
    "New Orleans Privateers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2443.png",
    "Houston Christian Huskies": "https://a.espncdn.com/i/teamlogos/ncaa/500/2277.png",
    "UIC Flames": "https://a.espncdn.com/i/teamlogos/ncaa/500/82.png",
    "Southern Miss": "https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png",
    "North Dakota State Bison": "https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png",
    "MONT": "https://a.espncdn.com/i/teamlogos/ncaa/500/149.png",
    "Arkansas-Pine Bluff Golden Lions": "https://a.espncdn.com/i/teamlogos/ncaa/500/2029.png",
    "California": "https://a.espncdn.com/i/teamlogos/ncaa/500/25.png",
    "South Alabama": "https://a.espncdn.com/i/teamlogos/ncaa/500/6.png",
    "ISU": "https://a.espncdn.com/i/teamlogos/ncaa/500/66.png",
    "SF": "https://a.espncdn.com/i/teamlogos/ncaa/500/2539.png",
    "Revolutionaries": "https://a.espncdn.com/i/teamlogos/ncaa/500/45.png",
    "W Michigan": "https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png",
    "UIC": "https://a.espncdn.com/i/teamlogos/ncaa/500/82.png",
    "George Mason Patriots": "https://a.espncdn.com/i/teamlogos/ncaa/500/2244.png",
    "BUF": "https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png",
    "WGA": "https://a.espncdn.com/i/teamlogos/ncaa/500/2698.png",
    "NMSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/166.png",
    "Mercer Bears": "https://a.espncdn.com/i/teamlogos/ncaa/500/2382.png",
    "Mastodons": "https://a.espncdn.com/i/teamlogos/ncaa/500/2870.png",
    "VMI": "https://a.espncdn.com/i/teamlogos/ncaa/500/2678.png",
    "Loyola MD": "https://a.espncdn.com/i/teamlogos/ncaa/500/2352.png",
    "Creighton": "https://a.espncdn.com/i/teamlogos/ncaa/500/156.png",
    "Ragin' Cajuns": "https://a.espncdn.com/i/teamlogos/ncaa/500/309.png",
    "Denver Pioneers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2172.png",
    "Stony Brook": "https://a.espncdn.com/i/teamlogos/ncaa/500/2619.png",
    "Braves": "https://a.espncdn.com/i/teamlogos/ncaa/500/71.png",
    "CREI": "https://a.espncdn.com/i/teamlogos/ncaa/500/156.png",
    "Hampton": "https://a.espncdn.com/i/teamlogos/ncaa/500/2261.png",
    "Syracuse Orange": "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
    "LAF": "https://a.espncdn.com/i/teamlogos/ncaa/500/322.png",
    "Red Storm": "https://a.espncdn.com/i/teamlogos/ncaa/500/2599.png",
    "Florida A&M": "https://a.espncdn.com/i/teamlogos/ncaa/500/50.png",
    "Texas Southern": "https://a.espncdn.com/i/teamlogos/ncaa/500/2640.png",
    "UTM": "https://a.espncdn.com/i/teamlogos/ncaa/500/2630.png",
    "North Carolina": "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
    "North Carolina Tar Heels": "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
    "E Michigan": "https://a.espncdn.com/i/teamlogos/ncaa/500/2199.png",
    "San Francisco": "https://a.espncdn.com/i/teamlogos/ncaa/500/2539.png",
    "Bears": "https://a.espncdn.com/i/teamlogos/ncaa/500/2458.png",
    "Gardner-Webb": "https://a.espncdn.com/i/teamlogos/ncaa/500/2241.png",
    "Portland State Vikings": "https://a.espncdn.com/i/teamlogos/ncaa/500/2502.png",
    "YSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2754.png",
    "MERC": "https://a.espncdn.com/i/teamlogos/ncaa/500/2385.png",
    "Wisconsin": "https://a.espncdn.com/i/teamlogos/ncaa/500/275.png",
    "Chicago State Cougars": "https://a.espncdn.com/i/teamlogos/ncaa/500/2130.png",
    "RUTG": "https://a.espncdn.com/i/teamlogos/ncaa/500/164.png",
    "Bakersfield": "https://a.espncdn.com/i/teamlogos/ncaa/500/2934.png",
    "MTSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png",
    "GT": "https://a.espncdn.com/i/teamlogos/ncaa/500/59.png",
    "Bradley": "https://a.espncdn.com/i/teamlogos/ncaa/500/71.png",
    "California Baptist Lancers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2856.png",
    "Kansas St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png",
    "Lancers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2344.png",
    "Le Moyne": "https://a.espncdn.com/i/teamlogos/ncaa/500/2330.png",
    "Golden Gophers": "https://a.espncdn.com/i/teamlogos/ncaa/500/135.png",
    "FAMU": "https://a.espncdn.com/i/teamlogos/ncaa/500/50.png",
    "QUIN": "https://a.espncdn.com/i/teamlogos/ncaa/500/2514.png",
    "TAR": "https://a.espncdn.com/i/teamlogos/ncaa/500/2627.png",
    "Georgia Southern Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/290.png",
    "Wolves": "https://a.espncdn.com/i/teamlogos/ncaa/500/2698.png",
    "Kennesaw St": "https://a.espncdn.com/i/teamlogos/ncaa/500/338.png",
    "Trojans": "https://a.espncdn.com/i/teamlogos/ncaa/500/30.png",
    "SEA": "https://a.espncdn.com/i/teamlogos/ncaa/500/2547.png",
    "Ole Miss Rebels": "https://a.espncdn.com/i/teamlogos/ncaa/500/145.png",
    "Dartmouth Big Green": "https://a.espncdn.com/i/teamlogos/ncaa/500/159.png",
    "UAB Blazers": "https://a.espncdn.com/i/teamlogos/ncaa/500/5.png",
    "Cyclones": "https://a.espncdn.com/i/teamlogos/ncaa/500/66.png",
    "Miners": "https://a.espncdn.com/i/teamlogos/ncaa/500/2638.png",
    "CARK": "https://a.espncdn.com/i/teamlogos/ncaa/500/2110.png",
    "Nittany Lions": "https://a.espncdn.com/i/teamlogos/ncaa/500/213.png",
    "Princeton": "https://a.espncdn.com/i/teamlogos/ncaa/500/163.png",
    "Duke": "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
    "Pennsylvania Quakers": "https://a.espncdn.com/i/teamlogos/ncaa/500/219.png",
    "Marquette": "https://a.espncdn.com/i/teamlogos/ncaa/500/269.png",
    "USF": "https://a.espncdn.com/i/teamlogos/ncaa/500/58.png",
    "Gauchos": "https://a.espncdn.com/i/teamlogos/ncaa/500/2540.png",
    "Oregon": "https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png",
    "FOR": "https://a.espncdn.com/i/teamlogos/ncaa/500/2230.png",
    "Oakland Golden Grizzlies": "https://a.espncdn.com/i/teamlogos/ncaa/500/2473.png",
    "Northern Kentucky Norse": "https://a.espncdn.com/i/teamlogos/ncaa/500/94.png",
    "TXST": "https://a.espncdn.com/i/teamlogos/ncaa/500/326.png",
    "Aggies": "https://a.espncdn.com/i/teamlogos/ncaa/500/328.png",
    "Xavier": "https://a.espncdn.com/i/teamlogos/ncaa/500/2752.png",
    "Ball State Cardinals": "https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png",
    "Air Force Falcons": "https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png",
    "EMU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2199.png",
    "Texans": "https://a.espncdn.com/i/teamlogos/ncaa/500/2627.png",
    "Lumberjacks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2617.png",
    "FLA": "https://a.espncdn.com/i/teamlogos/ncaa/500/57.png",
    "BYU": "https://a.espncdn.com/i/teamlogos/ncaa/500/252.png",
    "PRST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2502.png",
    "KENT": "https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png",
    "Broncos": "https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png",
    "FAIR": "https://a.espncdn.com/i/teamlogos/ncaa/500/2217.png",
    "UMass": "https://a.espncdn.com/i/teamlogos/ncaa/500/113.png",
    "MORE": "https://a.espncdn.com/i/teamlogos/ncaa/500/2413.png",
    "Minnesota Golden Gophers": "https://a.espncdn.com/i/teamlogos/ncaa/500/135.png",
    "ARIZ": "https://a.espncdn.com/i/teamlogos/ncaa/500/12.png",
    "Red Flash": "https://a.espncdn.com/i/teamlogos/ncaa/500/2598.png",
    "Bellarmine Knights": "https://a.espncdn.com/i/teamlogos/ncaa/500/91.png",
    "Chattanooga": "https://a.espncdn.com/i/teamlogos/ncaa/500/236.png",
    "San José St": "https://a.espncdn.com/i/teamlogos/ncaa/500/23.png",
    "Valparaiso Beacons": "https://a.espncdn.com/i/teamlogos/ncaa/500/2674.png",
    "IUIN": "https://a.espncdn.com/i/teamlogos/ncaa/500/85.png",
    "Loyola Maryland Greyhounds": "https://a.espncdn.com/i/teamlogos/ncaa/500/2352.png",
    "Arkansas St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png",
    "Hatters": "https://a.espncdn.com/i/teamlogos/ncaa/500/56.png",
    "Indiana State Sycamores": "https://a.espncdn.com/i/teamlogos/ncaa/500/282.png",
    "NEV": "https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png",
    "Tennessee": "https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png",
    "Toreros": "https://a.espncdn.com/i/teamlogos/ncaa/500/301.png",
    "Hurricanes": "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
    "Valparaiso": "https://a.espncdn.com/i/teamlogos/ncaa/500/2674.png",
    "Incarnate Word": "https://a.espncdn.com/i/teamlogos/ncaa/500/2916.png",
    "Saints": "https://a.espncdn.com/i/teamlogos/ncaa/500/2561.png",
    "Stephen F. Austin Lumberjacks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2617.png",
    "Towson Tigers": "https://a.espncdn.com/i/teamlogos/ncaa/500/119.png",
    "Iona": "https://a.espncdn.com/i/teamlogos/ncaa/500/314.png",
    "NICH": "https://a.espncdn.com/i/teamlogos/ncaa/500/2447.png",
    "Lipscomb Bisons": "https://a.espncdn.com/i/teamlogos/ncaa/500/288.png",
    "Buckeyes": "https://a.espncdn.com/i/teamlogos/ncaa/500/194.png",
    "Loyola Chicago Ramblers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2350.png",
    "Arizona State Sun Devils": "https://a.espncdn.com/i/teamlogos/ncaa/500/9.png",
    "Hokies": "https://a.espncdn.com/i/teamlogos/ncaa/500/259.png",
    "49ers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png",
    "MONM": "https://a.espncdn.com/i/teamlogos/ncaa/500/2405.png",
    "Fresno State Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/278.png",
    "Hoosiers": "https://a.espncdn.com/i/teamlogos/ncaa/500/84.png",
    "Green Bay": "https://a.espncdn.com/i/teamlogos/ncaa/500/2739.png",
    "Buffalo": "https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png",
    "App State Mountaineers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png",
    "CONN": "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png",
    "Pride": "https://a.espncdn.com/i/teamlogos/ncaa/500/2275.png",
    "Morehead St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2413.png",
    "Cal State Northridge Matadors": "https://a.espncdn.com/i/teamlogos/ncaa/500/2463.png",
    "JKST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2296.png",
    "C Arkansas": "https://a.espncdn.com/i/teamlogos/ncaa/500/2110.png",
    "New Haven Chargers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2441.png",
    "Marquette Golden Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/269.png",
    "N Illinois": "https://a.espncdn.com/i/teamlogos/ncaa/500/2459.png",
    "NJIT": "https://a.espncdn.com/i/teamlogos/ncaa/500/2885.png",
    "Southern Utah Thunderbirds": "https://a.espncdn.com/i/teamlogos/ncaa/500/253.png",
    "UConn Huskies": "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png",
    "UC San Diego": "https://a.espncdn.com/i/teamlogos/ncaa/500/28.png",
    "Florida International Panthers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2229.png",
    "Bluejays": "https://a.espncdn.com/i/teamlogos/ncaa/500/156.png",
    "LIP": "https://a.espncdn.com/i/teamlogos/ncaa/500/288.png",
    "Gamecocks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png",
    "Prairie View": "https://a.espncdn.com/i/teamlogos/ncaa/500/2504.png",
    "UCLA Bruins": "https://a.espncdn.com/i/teamlogos/ncaa/500/26.png",
    "STMN": "https://a.espncdn.com/i/teamlogos/ncaa/500/2900.png",
    "Stonehill Skyhawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/284.png",
    "Clemson": "https://a.espncdn.com/i/teamlogos/ncaa/500/228.png",
    "Georgia Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/59.png",
    "Ducks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png",
    "Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/43.png",
    "Delaware State Hornets": "https://a.espncdn.com/i/teamlogos/ncaa/500/2169.png",
    "Runnin' Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2241.png",
    "New Mexico": "https://a.espncdn.com/i/teamlogos/ncaa/500/167.png",
    "Davidson": "https://a.espncdn.com/i/teamlogos/ncaa/500/2166.png",
    "Bowling Green": "https://a.espncdn.com/i/teamlogos/ncaa/500/189.png",
    "NORF": "https://a.espncdn.com/i/teamlogos/ncaa/500/2450.png",
    "Tulsa Golden Hurricane": "https://a.espncdn.com/i/teamlogos/ncaa/500/202.png",
    "Privateers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2443.png",
    "HAMP": "https://a.espncdn.com/i/teamlogos/ncaa/500/2261.png",
    "Texas Southern Tigers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2640.png",
    "Army Black Knights": "https://a.espncdn.com/i/teamlogos/ncaa/500/349.png",
    "UCLA": "https://a.espncdn.com/i/teamlogos/ncaa/500/26.png",
    "Gonzaga Bulldogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png",
    "Demon Deacons": "https://a.espncdn.com/i/teamlogos/ncaa/500/154.png",
    "USD": "https://a.espncdn.com/i/teamlogos/ncaa/500/301.png",
    "Michigan": "https://a.espncdn.com/i/teamlogos/ncaa/500/130.png",
    "UL": "https://a.espncdn.com/i/teamlogos/ncaa/500/309.png",
    "TLSA": "https://a.espncdn.com/i/teamlogos/ncaa/500/202.png",
    "LAM": "https://a.espncdn.com/i/teamlogos/ncaa/500/2320.png",
    "LEH": "https://a.espncdn.com/i/teamlogos/ncaa/500/2329.png",
    "Rainbow Warriors": "https://a.espncdn.com/i/teamlogos/ncaa/500/62.png",
    "Ohio State Buckeyes": "https://a.espncdn.com/i/teamlogos/ncaa/500/194.png",
    "Iowa State Cyclones": "https://a.espncdn.com/i/teamlogos/ncaa/500/66.png",
    "Purple Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/315.png",
    "West Virginia Mountaineers": "https://a.espncdn.com/i/teamlogos/ncaa/500/277.png",
    "Belmont Bruins": "https://a.espncdn.com/i/teamlogos/ncaa/500/2057.png",
    "Miami": "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
    "South Florida": "https://a.espncdn.com/i/teamlogos/ncaa/500/58.png",
    "Samford": "https://a.espncdn.com/i/teamlogos/ncaa/500/2535.png",
    "Red Wolves": "https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png",
    "BELL": "https://a.espncdn.com/i/teamlogos/ncaa/500/91.png",
    "WRST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2750.png",
    "Robert Morris Colonials": "https://a.espncdn.com/i/teamlogos/ncaa/500/2523.png",
    "Wright State Raiders": "https://a.espncdn.com/i/teamlogos/ncaa/500/2750.png",
    "LEM": "https://a.espncdn.com/i/teamlogos/ncaa/500/2330.png",
    "BEL": "https://a.espncdn.com/i/teamlogos/ncaa/500/2057.png",
    "SMC": "https://a.espncdn.com/i/teamlogos/ncaa/500/2608.png",
    "Chicago St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2130.png",
    "Fordham": "https://a.espncdn.com/i/teamlogos/ncaa/500/2230.png",
    "Wake Forest Demon Deacons": "https://a.espncdn.com/i/teamlogos/ncaa/500/154.png",
    "Colorado": "https://a.espncdn.com/i/teamlogos/ncaa/500/38.png",
    "TCU Horned Frogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png",
    "Indiana Hoosiers": "https://a.espncdn.com/i/teamlogos/ncaa/500/84.png",
    "Vermont": "https://a.espncdn.com/i/teamlogos/ncaa/500/261.png",
    "Harvard Crimson": "https://a.espncdn.com/i/teamlogos/ncaa/500/108.png",
    "Abilene Chrstn": "https://a.espncdn.com/i/teamlogos/ncaa/500/2000.png",
    "Bison": "https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png",
    "Radford Highlanders": "https://a.espncdn.com/i/teamlogos/ncaa/500/2515.png",
    "Minnesota": "https://a.espncdn.com/i/teamlogos/ncaa/500/135.png",
    "Southern Miss Golden Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png",
    "Morehead State Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/2413.png",
    "Florida Gulf Coast Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/526.png",
    "DEL": "https://a.espncdn.com/i/teamlogos/ncaa/500/48.png",
    "BAY": "https://a.espncdn.com/i/teamlogos/ncaa/500/239.png",
    "Auburn": "https://a.espncdn.com/i/teamlogos/ncaa/500/2.png",
    "W&M": "https://a.espncdn.com/i/teamlogos/ncaa/500/2729.png",
    "Boilermakers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png",
    "The Citadel": "https://a.espncdn.com/i/teamlogos/ncaa/500/2643.png",
    "Harvard": "https://a.espncdn.com/i/teamlogos/ncaa/500/108.png",
    "UTA": "https://a.espncdn.com/i/teamlogos/ncaa/500/250.png",
    "Notre Dame Fighting Irish": "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png",
    "Fighting Hawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/155.png",
    "ULM": "https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png",
    "Monmouth Hawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2405.png",
    "Penn State": "https://a.espncdn.com/i/teamlogos/ncaa/500/213.png",
    "Boston College Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/103.png",
    "Miss Valley St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2400.png",
    "UL Monroe Warhawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png",
    "Arizona": "https://a.espncdn.com/i/teamlogos/ncaa/500/12.png",
    "TTU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png",
    "UNC Asheville": "https://a.espncdn.com/i/teamlogos/ncaa/500/2427.png",
    "Portland": "https://a.espncdn.com/i/teamlogos/ncaa/500/2501.png",
    "CAN": "https://a.espncdn.com/i/teamlogos/ncaa/500/2099.png",
    "Incarnate Word Cardinals": "https://a.espncdn.com/i/teamlogos/ncaa/500/2916.png",
    "Saint Louis Billikens": "https://a.espncdn.com/i/teamlogos/ncaa/500/139.png",
    "Canisius Golden Griffins": "https://a.espncdn.com/i/teamlogos/ncaa/500/2099.png",
    "Duquesne": "https://a.espncdn.com/i/teamlogos/ncaa/500/2184.png",
    "Chattanooga Mocs": "https://a.espncdn.com/i/teamlogos/ncaa/500/236.png",
    "Mustangs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png",
    "UC Irvine": "https://a.espncdn.com/i/teamlogos/ncaa/500/300.png",
    "PRIN": "https://a.espncdn.com/i/teamlogos/ncaa/500/163.png",
    "Virginia Tech Hokies": "https://a.espncdn.com/i/teamlogos/ncaa/500/259.png",
    "West Georgia Wolves": "https://a.espncdn.com/i/teamlogos/ncaa/500/2698.png",
    "Georgetown": "https://a.espncdn.com/i/teamlogos/ncaa/500/46.png",
    "Northwestern": "https://a.espncdn.com/i/teamlogos/ncaa/500/77.png",
    "New Hampshire": "https://a.espncdn.com/i/teamlogos/ncaa/500/160.png",
    "WIN": "https://a.espncdn.com/i/teamlogos/ncaa/500/2737.png",
    "Bellarmine": "https://a.espncdn.com/i/teamlogos/ncaa/500/91.png",
    "NC State Wolfpack": "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
    "UT Arlington Mavericks": "https://a.espncdn.com/i/teamlogos/ncaa/500/250.png",
    "BRY": "https://a.espncdn.com/i/teamlogos/ncaa/500/2803.png",
    "McNeese": "https://a.espncdn.com/i/teamlogos/ncaa/500/2377.png",
    "Army": "https://a.espncdn.com/i/teamlogos/ncaa/500/349.png",
    "Sycamores": "https://a.espncdn.com/i/teamlogos/ncaa/500/282.png",
    "Skyhawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2630.png",
    "Minutemen": "https://a.espncdn.com/i/teamlogos/ncaa/500/113.png",
    "St. Thomas-Minnesota Tommies": "https://a.espncdn.com/i/teamlogos/ncaa/500/2900.png",
    "HC": "https://a.espncdn.com/i/teamlogos/ncaa/500/107.png",
    "Colorado Buffaloes": "https://a.espncdn.com/i/teamlogos/ncaa/500/38.png",
    "Alabama State Hornets": "https://a.espncdn.com/i/teamlogos/ncaa/500/2011.png",
    "Warriors": "https://a.espncdn.com/i/teamlogos/ncaa/500/2771.png",
    "Hilltoppers": "https://a.espncdn.com/i/teamlogos/ncaa/500/98.png",
    "Blue Hose": "https://a.espncdn.com/i/teamlogos/ncaa/500/2506.png",
    "New Mexico St": "https://a.espncdn.com/i/teamlogos/ncaa/500/166.png",
    "Penguins": "https://a.espncdn.com/i/teamlogos/ncaa/500/2754.png",
    "Elon": "https://a.espncdn.com/i/teamlogos/ncaa/500/2210.png",
    "Razorbacks": "https://a.espncdn.com/i/teamlogos/ncaa/500/8.png",
    "Broncs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2520.png",
    "South Dakota State Jackrabbits": "https://a.espncdn.com/i/teamlogos/ncaa/500/2571.png",
    "Tommies": "https://a.espncdn.com/i/teamlogos/ncaa/500/2900.png",
    "William & Mary Tribe": "https://a.espncdn.com/i/teamlogos/ncaa/500/2729.png",
    "Blazers": "https://a.espncdn.com/i/teamlogos/ncaa/500/5.png",
    "James Madison": "https://a.espncdn.com/i/teamlogos/ncaa/500/256.png",
    "Furman": "https://a.espncdn.com/i/teamlogos/ncaa/500/231.png",
    "DSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2169.png",
    "Saint Mary's": "https://a.espncdn.com/i/teamlogos/ncaa/500/2608.png",
    "USM": "https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png",
    "Quinnipiac Bobcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/2514.png",
    "Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/2737.png",
    "Holy Cross": "https://a.espncdn.com/i/teamlogos/ncaa/500/107.png",
    "Nevada Wolf Pack": "https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png",
    "MCN": "https://a.espncdn.com/i/teamlogos/ncaa/500/2377.png",
    "Grand Canyon": "https://a.espncdn.com/i/teamlogos/ncaa/500/2253.png",
    "Idaho Vandals": "https://a.espncdn.com/i/teamlogos/ncaa/500/70.png",
    "New Haven": "https://a.espncdn.com/i/teamlogos/ncaa/500/2441.png",
    "American University Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/44.png",
    "FGCU": "https://a.espncdn.com/i/teamlogos/ncaa/500/526.png",
    "UTEP Miners": "https://a.espncdn.com/i/teamlogos/ncaa/500/2638.png",
    "LMU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2351.png",
    "E Texas A&M": "https://a.espncdn.com/i/teamlogos/ncaa/500/2837.png",
    "Dolphins": "https://a.espncdn.com/i/teamlogos/ncaa/500/2330.png",
    "Charleston Southern Buccaneers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2127.png",
    "SF Austin": "https://a.espncdn.com/i/teamlogos/ncaa/500/2617.png",
    "Texas A&M": "https://a.espncdn.com/i/teamlogos/ncaa/500/245.png",
    "NKU": "https://a.espncdn.com/i/teamlogos/ncaa/500/94.png",
    "S Dakota St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2571.png",
    "ARST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png",
    "RAD": "https://a.espncdn.com/i/teamlogos/ncaa/500/2515.png",
    "Northern Arizona Lumberjacks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2464.png",
    "Wyoming Cowboys": "https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png",
    "Ole Miss": "https://a.espncdn.com/i/teamlogos/ncaa/500/145.png",
    "Utah State Aggies": "https://a.espncdn.com/i/teamlogos/ncaa/500/328.png",
    "South Carolina Gamecocks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png",
    "Tigers": "https://a.espncdn.com/i/teamlogos/ncaa/500/119.png",
    "MIA": "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
    "SIU": "https://a.espncdn.com/i/teamlogos/ncaa/500/79.png",
    "Wolf Pack": "https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png",
    "Tritons": "https://a.espncdn.com/i/teamlogos/ncaa/500/28.png",
    "DAV": "https://a.espncdn.com/i/teamlogos/ncaa/500/2166.png",
    "FDU": "https://a.espncdn.com/i/teamlogos/ncaa/500/161.png",
    "MUR": "https://a.espncdn.com/i/teamlogos/ncaa/500/93.png",
    "Golden Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/2635.png",
    "Saint Mary's Gaels": "https://a.espncdn.com/i/teamlogos/ncaa/500/2608.png",
    "NEB": "https://a.espncdn.com/i/teamlogos/ncaa/500/158.png",
    "Billikens": "https://a.espncdn.com/i/teamlogos/ncaa/500/139.png",
    "Utah Valley": "https://a.espncdn.com/i/teamlogos/ncaa/500/3084.png",
    "Governors": "https://a.espncdn.com/i/teamlogos/ncaa/500/2046.png",
    "San Diego St": "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png",
    "Rockets": "https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png",
    "NCAT": "https://a.espncdn.com/i/teamlogos/ncaa/500/2448.png",
    "WAG": "https://a.espncdn.com/i/teamlogos/ncaa/500/2681.png",
    "Beacons": "https://a.espncdn.com/i/teamlogos/ncaa/500/2674.png",
    "Bowling Green Falcons": "https://a.espncdn.com/i/teamlogos/ncaa/500/189.png",
    "NC Central": "https://a.espncdn.com/i/teamlogos/ncaa/500/2428.png",
    "Islanders": "https://a.espncdn.com/i/teamlogos/ncaa/500/357.png",
    "Wyoming": "https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png",
    "UC Davis Aggies": "https://a.espncdn.com/i/teamlogos/ncaa/500/302.png",
    "Purdue FW": "https://a.espncdn.com/i/teamlogos/ncaa/500/2870.png",
    "UMBC": "https://a.espncdn.com/i/teamlogos/ncaa/500/2378.png",
    "LBSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/299.png",
    "Villanova Wildcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/222.png",
    "GTWN": "https://a.espncdn.com/i/teamlogos/ncaa/500/46.png",
    "UNCO": "https://a.espncdn.com/i/teamlogos/ncaa/500/2458.png",
    "Stanford Cardinal": "https://a.espncdn.com/i/teamlogos/ncaa/500/24.png",
    "Virginia Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/259.png",
    "Grand Canyon Lopes": "https://a.espncdn.com/i/teamlogos/ncaa/500/2253.png",
    "TA&M": "https://a.espncdn.com/i/teamlogos/ncaa/500/245.png",
    "Coastal Carolina Chanticleers": "https://a.espncdn.com/i/teamlogos/ncaa/500/324.png",
    "Wagner": "https://a.espncdn.com/i/teamlogos/ncaa/500/2681.png",
    "SPU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2612.png",
    "Owls": "https://a.espncdn.com/i/teamlogos/ncaa/500/218.png",
    "West Georgia": "https://a.espncdn.com/i/teamlogos/ncaa/500/2698.png",
    "Crusaders": "https://a.espncdn.com/i/teamlogos/ncaa/500/107.png",
    "UTU": "https://a.espncdn.com/i/teamlogos/ncaa/500/3101.png",
    "AKR": "https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png",
    "SC Upstate": "https://a.espncdn.com/i/teamlogos/ncaa/500/2908.png",
    "Columbia Lions": "https://a.espncdn.com/i/teamlogos/ncaa/500/171.png",
    "Cleveland St": "https://a.espncdn.com/i/teamlogos/ncaa/500/325.png",
    "Youngstown State Penguins": "https://a.espncdn.com/i/teamlogos/ncaa/500/2754.png",
    "Gaels": "https://a.espncdn.com/i/teamlogos/ncaa/500/2608.png",
    "Green Wave": "https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png",
    "PEPP": "https://a.espncdn.com/i/teamlogos/ncaa/500/2492.png",
    "Missouri St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2623.png",
    "Washington Huskies": "https://a.espncdn.com/i/teamlogos/ncaa/500/264.png",
    "PORT": "https://a.espncdn.com/i/teamlogos/ncaa/500/2501.png",
    "GONZ": "https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png",
    "Arizona St": "https://a.espncdn.com/i/teamlogos/ncaa/500/9.png",
    "Sacramento St": "https://a.espncdn.com/i/teamlogos/ncaa/500/16.png",
    "Richmond Spiders": "https://a.espncdn.com/i/teamlogos/ncaa/500/257.png",
    "L-MD": "https://a.espncdn.com/i/teamlogos/ncaa/500/2352.png",
    "Eastern Michigan Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/2199.png",
    "LR": "https://a.espncdn.com/i/teamlogos/ncaa/500/2031.png",
    "Charlotte": "https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png",
    "Iowa Hawkeyes": "https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png",
    "Charleston Cougars": "https://a.espncdn.com/i/teamlogos/ncaa/500/232.png",
    "Cal State Fullerton Titans": "https://a.espncdn.com/i/teamlogos/ncaa/500/2239.png",
    "MRST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2368.png",
    "Black Knights": "https://a.espncdn.com/i/teamlogos/ncaa/500/349.png",
    "New Mexico State Aggies": "https://a.espncdn.com/i/teamlogos/ncaa/500/166.png",
    "Hofstra Pride": "https://a.espncdn.com/i/teamlogos/ncaa/500/2275.png",
    "Tennessee Tech Golden Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/2635.png",
    "Seattle U": "https://a.espncdn.com/i/teamlogos/ncaa/500/2547.png",
    "Rhode Island Rams": "https://a.espncdn.com/i/teamlogos/ncaa/500/227.png",
    "KC": "https://a.espncdn.com/i/teamlogos/ncaa/500/140.png",
    "Miami Hurricanes": "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
    "EIU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2197.png",
    "Wisconsin Badgers": "https://a.espncdn.com/i/teamlogos/ncaa/500/275.png",
    "ILL": "https://a.espncdn.com/i/teamlogos/ncaa/500/356.png",
    "Jacksonville Dolphins": "https://a.espncdn.com/i/teamlogos/ncaa/500/294.png",
    "Fairfield": "https://a.espncdn.com/i/teamlogos/ncaa/500/2217.png",
    "Wichita St": "https://a.espncdn.com/i/teamlogos/ncaa/500/2724.png",
    "Horned Frogs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png",
    "TENN": "https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png",
    "Jackrabbits": "https://a.espncdn.com/i/teamlogos/ncaa/500/2571.png",
    "SDAK": "https://a.espncdn.com/i/teamlogos/ncaa/500/233.png",
    "Baylor": "https://a.espncdn.com/i/teamlogos/ncaa/500/239.png",
    "WSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/265.png",
    "Austin Peay": "https://a.espncdn.com/i/teamlogos/ncaa/500/2046.png",
    "Oklahoma St": "https://a.espncdn.com/i/teamlogos/ncaa/500/197.png",
    "UL Monroe": "https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png",
    "Louisville": "https://a.espncdn.com/i/teamlogos/ncaa/500/97.png",
    "Montana": "https://a.espncdn.com/i/teamlogos/ncaa/500/149.png",
    "Montana Grizzlies": "https://a.espncdn.com/i/teamlogos/ncaa/500/149.png",
    "Golden Griffins": "https://a.espncdn.com/i/teamlogos/ncaa/500/2099.png",
    "Mount St. Mary's Mountaineers": "https://a.espncdn.com/i/teamlogos/ncaa/500/116.png",
    "North Carolina Central Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/2428.png",
    "Miami (OH) RedHawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/193.png",
    "Abilene Christian Wildcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/2000.png",
    "UMass Lowell": "https://a.espncdn.com/i/teamlogos/ncaa/500/2349.png",
    "Arkansas Razorbacks": "https://a.espncdn.com/i/teamlogos/ncaa/500/8.png",
    "SHU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2529.png",
    "Lipscomb": "https://a.espncdn.com/i/teamlogos/ncaa/500/288.png",
    "Vermont Catamounts": "https://a.espncdn.com/i/teamlogos/ncaa/500/261.png",
    "Houston Cougars": "https://a.espncdn.com/i/teamlogos/ncaa/500/248.png",
    "George Mason": "https://a.espncdn.com/i/teamlogos/ncaa/500/2244.png",
    "KENN": "https://a.espncdn.com/i/teamlogos/ncaa/500/338.png",
    "West Virginia": "https://a.espncdn.com/i/teamlogos/ncaa/500/277.png",
    "C Michigan": "https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png",
    "Colorado State Rams": "https://a.espncdn.com/i/teamlogos/ncaa/500/36.png",
    "Fresno St": "https://a.espncdn.com/i/teamlogos/ncaa/500/278.png",
    "Idaho St": "https://a.espncdn.com/i/teamlogos/ncaa/500/304.png",
    "SIE": "https://a.espncdn.com/i/teamlogos/ncaa/500/2561.png",
    "Hornets": "https://a.espncdn.com/i/teamlogos/ncaa/500/16.png",
    "Gonzaga": "https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png",
    "Oral Roberts Golden Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/198.png",
    "Lobos": "https://a.espncdn.com/i/teamlogos/ncaa/500/167.png",
    "Old Dominion": "https://a.espncdn.com/i/teamlogos/ncaa/500/295.png",
    "Delaware Blue Hens": "https://a.espncdn.com/i/teamlogos/ncaa/500/48.png",
    "East Tennessee State Buccaneers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2193.png",
    "UNO": "https://a.espncdn.com/i/teamlogos/ncaa/500/2443.png",
    "TNST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2634.png",
    "SE Louisiana Lions": "https://a.espncdn.com/i/teamlogos/ncaa/500/2545.png",
    "Nicholls": "https://a.espncdn.com/i/teamlogos/ncaa/500/2447.png",
    "EVAN": "https://a.espncdn.com/i/teamlogos/ncaa/500/339.png",
    "Miami OH": "https://a.espncdn.com/i/teamlogos/ncaa/500/193.png",
    "Purdue Boilermakers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png",
    "UMES": "https://a.espncdn.com/i/teamlogos/ncaa/500/2379.png",
    "Bucknell": "https://a.espncdn.com/i/teamlogos/ncaa/500/2083.png",
    "Cornell": "https://a.espncdn.com/i/teamlogos/ncaa/500/172.png",
    "Longhorns": "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
    "MD": "https://a.espncdn.com/i/teamlogos/ncaa/500/120.png",
    "UCR": "https://a.espncdn.com/i/teamlogos/ncaa/500/27.png",
    "Commodores": "https://a.espncdn.com/i/teamlogos/ncaa/500/238.png",
    "KSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png",
    "UTC": "https://a.espncdn.com/i/teamlogos/ncaa/500/236.png",
    "Wagner Seahawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2681.png",
    "Alcorn State Braves": "https://a.espncdn.com/i/teamlogos/ncaa/500/2016.png",
    "Virginia Cavaliers": "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
    "GAST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png",
    "Ramblers": "https://a.espncdn.com/i/teamlogos/ncaa/500/2350.png",
    "Lafayette": "https://a.espncdn.com/i/teamlogos/ncaa/500/322.png",
    "Jayhawks": "https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png",
    "Montana St": "https://a.espncdn.com/i/teamlogos/ncaa/500/147.png",
    "CIN": "https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png",
    "Winthrop Eagles": "https://a.espncdn.com/i/teamlogos/ncaa/500/2737.png",
    "ALCN": "https://a.espncdn.com/i/teamlogos/ncaa/500/2016.png",
    "ALST": "https://a.espncdn.com/i/teamlogos/ncaa/500/2011.png",
    "WIU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2710.png",
    "DRKE": "https://a.espncdn.com/i/teamlogos/ncaa/500/2181.png",
    "COLG": "https://a.espncdn.com/i/teamlogos/ncaa/500/2142.png",
    "Syracuse": "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
    "Temple": "https://a.espncdn.com/i/teamlogos/ncaa/500/218.png",
    "Buffaloes": "https://a.espncdn.com/i/teamlogos/ncaa/500/38.png",
    "Cincinnati Bearcats": "https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png",
    "Tar Heels": "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
    "Marist": "https://a.espncdn.com/i/teamlogos/ncaa/500/2368.png",
    "Charleston So": "https://a.espncdn.com/i/teamlogos/ncaa/500/2127.png",
    "WIS": "https://a.espncdn.com/i/teamlogos/ncaa/500/275.png",
    "Binghamton": "https://a.espncdn.com/i/teamlogos/ncaa/500/2066.png",
    "Illinois": "https://a.espncdn.com/i/teamlogos/ncaa/500/356.png",
    "Merrimack Warriors": "https://a.espncdn.com/i/teamlogos/ncaa/500/2771.png",
    "Rider Broncs": "https://a.espncdn.com/i/teamlogos/ncaa/500/2520.png",
    "Green Bay Phoenix": "https://a.espncdn.com/i/teamlogos/ncaa/500/2739.png",
    "ODU": "https://a.espncdn.com/i/teamlogos/ncaa/500/295.png",
    "Blue Demons": "https://a.espncdn.com/i/teamlogos/ncaa/500/305.png",
    "Wake Forest": "https://a.espncdn.com/i/teamlogos/ncaa/500/154.png",
    "IU": "https://a.espncdn.com/i/teamlogos/ncaa/500/84.png",
    "HOF": "https://a.espncdn.com/i/teamlogos/ncaa/500/2275.png",
    "MORG": "https://a.espncdn.com/i/teamlogos/ncaa/500/2415.png",
    "North Texas Mean Green": "https://a.espncdn.com/i/teamlogos/ncaa/500/249.png",
    "Santa Clara": "https://a.espncdn.com/i/teamlogos/ncaa/500/2541.png",
    "PSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/213.png",
    "Bryant": "https://a.espncdn.com/i/teamlogos/ncaa/500/2803.png",
    "Dartmouth": "https://a.espncdn.com/i/teamlogos/ncaa/500/159.png",
};

function getTeamLogo(teamName) {
    if (!teamName) return '';
    // exact match
    if (TEAM_LOGOS[teamName]) return TEAM_LOGOS[teamName];
    // try removing 'University' or common prefixes/suffixes if needed, 
    // but for now relying on the extensive list.
    return '';
}
